// This file was auto-generated by Fern from our API Definition.

export const ApifreaksApiEnvironment = {
    Default: "https://api.apifreaks.com",
} as const;

export type ApifreaksApiEnvironment = typeof ApifreaksApiEnvironment.Default;
