// This file was auto-generated by Fern from our API Definition.

export const AirQualityRequestPrecision = {
    Hourly: "hourly",
} as const;
export type AirQualityRequestPrecision = (typeof AirQualityRequestPrecision)[keyof typeof AirQualityRequestPrecision];
