// This file was auto-generated by Fern from our API Definition.

export const AirQualityRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type AirQualityRequestFormat = (typeof AirQualityRequestFormat)[keyof typeof AirQualityRequestFormat];
