// This file was auto-generated by Fern from our API Definition.

export interface AsnWhoisLookupResponse {
    asNumber: string;
    asName: string;
    orgName: string;
    description?: string | undefined;
    orgHandle: string;
    country: string;
    domain?: string | undefined;
    website?: string | undefined;
    allocationStatus: string;
    numOfIPv4Routes: string;
    numOfIPv6Routes: string;
    whoisHost: string;
    dateAllocated?: string | undefined;
    type: string;
    routeObjects: AsnWhoisLookupResponse.RouteObjects.Item[];
    whoisResponse: string;
    downstreams: AsnWhoisLookupResponse.Downstreams.Item[];
    parsedWhoisResponse: AsnWhoisLookupResponse.ParsedWhoisResponse;
    upstreams: AsnWhoisLookupResponse.Upstreams.Item[];
    peers: AsnWhoisLookupResponse.Peers.Item[];
    contacts: AsnWhoisLookupResponse.Contacts;
    legacyRoutes: string[];
    whois_raw_response?: string | undefined;
    r_whois_raw_response?: string | undefined;
    query_time?: string | undefined;
}

export namespace AsnWhoisLookupResponse {
    export type RouteObjects = RouteObjects.Item[];

    export namespace RouteObjects {
        export interface Item {
            route: string;
            origin: string;
            originName: string;
            isp: string;
            numberOfIps: number;
        }
    }

    export type Downstreams = Downstreams.Item[];

    export namespace Downstreams {
        export interface Item {
            asNumber?: string | undefined;
            description?: string | undefined;
            country?: string | undefined;
        }
    }

    export interface ParsedWhoisResponse {
        status: boolean;
        whois_server: string;
        aut_nums: ParsedWhoisResponse.AutNums.Item[];
        organization: ParsedWhoisResponse.Organization;
        technical_contacts: ParsedWhoisResponse.TechnicalContacts.Item[];
        abuse_contacts: ParsedWhoisResponse.AbuseContacts.Item[];
    }

    export namespace ParsedWhoisResponse {
        export type AutNums = AutNums.Item[];

        export namespace AutNums {
            export interface Item {
                aut_num: string;
                as_handle: string;
                as_name: string;
                tech_contacts: string[];
                abuse_contacts: string[];
                date_created: string;
                date_updated: string;
                source: string;
                description?: string | undefined;
                country?: string | undefined;
                status?: string[] | undefined;
                member_of?: string[] | undefined;
                import_via?: string[] | undefined;
                import?: string[] | undefined;
                mp_import?: string[] | undefined;
                export_via?: string[] | undefined;
                export?: string[] | undefined;
                mp_export?: string[] | undefined;
                default?: string[] | undefined;
                mp_default?: string[] | undefined;
                organization?: string | undefined;
                sponsoring_organization?: string | undefined;
                admin_contacts?: string[] | undefined;
            }
        }

        export interface Organization {
            handle?: string | undefined;
            name?: string | undefined;
            address?: string[] | undefined;
            street?: string | undefined;
            city?: string | undefined;
            state?: string | undefined;
            zip_code?: string | undefined;
            country?: string[] | undefined;
            addressCountry?: string | undefined;
            date_created?: string | undefined;
            date_updated?: string | undefined;
            source?: string | undefined;
        }

        export type TechnicalContacts = TechnicalContacts.Item[];

        export namespace TechnicalContacts {
            export interface Item {
                handle: string;
                name: string;
                email: string[];
                phone?: string[] | undefined;
                source?: string | undefined;
            }
        }

        export type AbuseContacts = AbuseContacts.Item[];

        export namespace AbuseContacts {
            export interface Item {
                handle: string;
                name: string;
                email: string[];
                phone?: string[] | undefined;
                source?: string | undefined;
            }
        }
    }

    export type Upstreams = Upstreams.Item[];

    export namespace Upstreams {
        export interface Item {
            asNumber: string;
            description: string;
            country: string;
        }
    }

    export type Peers = Peers.Item[];

    export namespace Peers {
        export interface Item {
            asNumber: string;
            description: string;
            country: string;
        }
    }

    export interface Contacts {
        emailContacts: string[];
        abuseContacts: string[];
    }
}
