// This file was auto-generated by Fern from our API Definition.

export const AsnWhoisLookupRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type AsnWhoisLookupRequestFormat =
    (typeof AsnWhoisLookupRequestFormat)[keyof typeof AsnWhoisLookupRequestFormat];
