// This file was auto-generated by Fern from our API Definition.

export const AstronomyLookupV2RequestLang = {
    En: "en",
    De: "de",
    Ru: "ru",
    Ja: "ja",
    Fr: "fr",
    Cn: "cn",
    Es: "es",
    Cs: "cs",
    It: "it",
    Ko: "ko",
    Fa: "fa",
    Pt: "pt",
} as const;
export type AstronomyLookupV2RequestLang =
    (typeof AstronomyLookupV2RequestLang)[keyof typeof AstronomyLookupV2RequestLang];
