// This file was auto-generated by Fern from our API Definition.

export const AstronomyLookupV2RequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type AstronomyLookupV2RequestFormat =
    (typeof AstronomyLookupV2RequestFormat)[keyof typeof AstronomyLookupV2RequestFormat];
