// This file was auto-generated by Fern from our API Definition.

export const AstronomyLookupRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type AstronomyLookupRequestFormat =
    (typeof AstronomyLookupRequestFormat)[keyof typeof AstronomyLookupRequestFormat];
