// This file was auto-generated by Fern from our API Definition.

/**
 * Astronomy data response containing location information and astronomical data.
 */
export interface AstronomyLookupV2Response {
    /** IPv4 or IPv6 address used for the geo-IP lookup. Present when the ip parameter is passed explicitly, or when no location, lat/long, or ip parameter is supplied at all (the API falls back to the requesting client's IP address). Absent when location or lat/long is used. */
    ip?: string | undefined;
    /** Geographic location information for the astronomy calculation. The set of populated fields depends on which lookup mode the request used: (1) location param (geocode-by-address) returns location_string plus a basic field set (country_name, state_prov, city, locality, latitude, longitude, elevation); (2) lat + long params (geocode-by-coordinates) returns the same basic field set minus location_string, and locality may be an empty string when the coordinates don't resolve to a named sub-area; (3) ip param, or no location/lat/long/ip param at all (falls back to geo-IP lookup of the client's IP), returns the full geo-IP field set — continent_code, continent_name, country_code2, country_code3, country_name_official, is_eu, state_code, district, zipcode — in addition to the basic fields, but never location_string. elevation can be an empty string when elevation data is unavailable for the resolved location. */
    location?: AstronomyLookupV2Response.Location | undefined;
    /** Complete astronomical data for the specified location and date. */
    astronomy: AstronomyLookupV2Response.Astronomy;
}

export namespace AstronomyLookupV2Response {
    /**
     * Geographic location information for the astronomy calculation. The set of populated fields depends on which lookup mode the request used: (1) location param (geocode-by-address) returns location_string plus a basic field set (country_name, state_prov, city, locality, latitude, longitude, elevation); (2) lat + long params (geocode-by-coordinates) returns the same basic field set minus location_string, and locality may be an empty string when the coordinates don't resolve to a named sub-area; (3) ip param, or no location/lat/long/ip param at all (falls back to geo-IP lookup of the client's IP), returns the full geo-IP field set — continent_code, continent_name, country_code2, country_code3, country_name_official, is_eu, state_code, district, zipcode — in addition to the basic fields, but never location_string. elevation can be an empty string when elevation data is unavailable for the resolved location.
     */
    export interface Location {
        /** The location query parameter echoed back as-is. Present only for geocode-by-address lookups (location param); absent for lat/long and ip-based lookups. */
        location_string?: string | undefined;
        /** The two-letter code of the continent (e.g., "NA"). Geo-IP field only: present for ip param or default client-IP lookups; absent for location/lat/long geocode lookups. */
        continent_code?: string | undefined;
        /** The full name of the continent (e.g., "North America"). Geo-IP field only: present for ip param or default client-IP lookups; absent for location/lat/long geocode lookups. */
        continent_name?: string | undefined;
        /** The ISO 3166-1 alpha-2 two-letter country code (e.g., "US"). Geo-IP field only: present for ip param or default client-IP lookups; absent for location/lat/long geocode lookups. */
        country_code2?: string | undefined;
        /** The ISO 3166-1 alpha-3 three-letter country code (e.g., "USA"). Geo-IP field only: present for ip param or default client-IP lookups; absent for location/lat/long geocode lookups. */
        country_code3?: string | undefined;
        /** The common name of the country (e.g., "United States"). Present in all lookup modes. */
        country_name?: string | undefined;
        /** The official full name of the country (e.g., "United States of America"). Geo-IP field only: present for ip param or default client-IP lookups; absent for location/lat/long geocode lookups. */
        country_name_official?: string | undefined;
        /** Whether the country belongs to the European Union. Geo-IP field only: present for ip param or default client-IP lookups; absent for location/lat/long geocode lookups. */
        is_eu?: boolean | undefined;
        /** Name of the state/province/region. Present in all lookup modes. */
        state_prov?: string | undefined;
        /** Code of the state/province/region. Geo-IP field only: present for ip param or default client-IP lookups; absent for location/lat/long geocode lookups. */
        state_code?: string | undefined;
        /** Name of the district or county. Geo-IP field only: present for ip param or default client-IP lookups; absent for location/lat/long geocode lookups. */
        district?: string | undefined;
        /** Name of the city. Present in all lookup modes. */
        city?: string | undefined;
        /** ZIP/Postal code of the place. Geo-IP field only: present for ip param or default client-IP lookups; absent for location/lat/long geocode lookups. */
        zipcode?: string | undefined;
        /** The geographic latitude of the location. Present in all lookup modes. */
        latitude: string;
        /** The geographic longitude of the location. Present in all lookup modes. */
        longitude: string;
        /** Smaller area, part or region of a city. Present in all lookup modes, but may be an empty string for lat/long or geo-IP lookups when no named sub-area resolves. */
        locality?: string | undefined;
        /** The elevation of the geographical location, in meters. Present in all lookup modes, but may be an empty string when elevation data is unavailable for the resolved location. */
        elevation?: string | undefined;
    }

    /**
     * Complete astronomical data for the specified location and date.
     */
    export interface Astronomy {
        /** Appears (with the provided value) only when the user includes a time_zone in the query to specify which time to observe. */
        time_zone?: string | undefined;
        /** The date astronomy data was calculated for. Defaults to today's date; reflects the date query parameter's value when that parameter is supplied. */
        date: string;
        /** The current time */
        current_time: string;
        /** The time of midnight (solar-based) */
        mid_night: string;
        /** The time when night ends (start of astronomical twilight) */
        night_end: string;
        /** Morning astronomical data including twilight, blue hour, and golden hour times. */
        morning: Astronomy.Morning;
        /** The time of sunrise */
        sunrise: string;
        /** The time of sunset */
        sunset: string;
        /** Evening astronomical data including golden hour, blue hour, and twilight times. */
        evening: Astronomy.Evening;
        /** The time when night begins (end of astronomical twilight) */
        night_begin: string;
        /** The current status of the sun (e.g., "rising", "setting", "-") */
        sun_status: string;
        /** The time when the sun reaches its highest point in the sky */
        solar_noon: string;
        /** The total duration of daylight */
        day_length: string;
        /** The altitude angle of the sun above the horizon in degrees */
        sun_altitude: number;
        /** The distance from the Earth to the sun in kilometers */
        sun_distance: number;
        /** The azimuth angle of the sun in degrees from true north */
        sun_azimuth: number;
        /** The current phase of the moon (e.g., "WAXING_GIBBOUS") */
        moon_phase: string;
        /** The time of moonrise */
        moonrise: string;
        /** The time of moonset */
        moonset: string;
        /** The current status of the moon (e.g., "rising", "setting", "-") */
        moon_status: string;
        /** The altitude angle of the moon above the horizon in degrees */
        moon_altitude: number;
        /** The distance from the Earth to the moon in kilometers */
        moon_distance: number;
        /** The azimuth angle of the moon in degrees from true north */
        moon_azimuth: number;
        /** The parallactic angle of the moon in degrees */
        moon_parallactic_angle: number;
        /** The percentage of the moon illuminated by sunlight. A negative value indicates the moon is in a waning phase. */
        moon_illumination_percentage: string;
        /** The geometric angle of the moon relative to the observer */
        moon_angle: number;
    }

    export namespace Astronomy {
        /**
         * Morning astronomical data including twilight, blue hour, and golden hour times.
         */
        export interface Morning {
            /** The start time of astronomical twilight in the morning */
            astronomical_twilight_begin: string;
            /** The end time of astronomical twilight in the morning */
            astronomical_twilight_end: string;
            /** The start time of nautical twilight in the morning */
            nautical_twilight_begin: string;
            /** The end time of nautical twilight in the morning */
            nautical_twilight_end: string;
            /** The start time of civil twilight in the morning */
            civil_twilight_begin: string;
            /** The end time of civil twilight in the morning */
            civil_twilight_end: string;
            /** The beginning of the blue hour in the morning */
            blue_hour_begin: string;
            /** The end of the blue hour in the morning */
            blue_hour_end: string;
            /** The beginning of the golden hour in the morning */
            golden_hour_begin: string;
            /** The end of the golden hour in the morning */
            golden_hour_end: string;
        }

        /**
         * Evening astronomical data including golden hour, blue hour, and twilight times.
         */
        export interface Evening {
            /** The beginning of the golden hour in the evening */
            golden_hour_begin: string;
            /** The end of the golden hour in the evening */
            golden_hour_end: string;
            /** The beginning of the blue hour in the evening */
            blue_hour_begin: string;
            /** The end of the blue hour in the evening */
            blue_hour_end: string;
            /** The start of civil twilight in the evening */
            civil_twilight_begin: string;
            /** The end of civil twilight in the evening */
            civil_twilight_end: string;
            /** The start of nautical twilight in the evening */
            nautical_twilight_begin: string;
            /** The end of nautical twilight in the evening */
            nautical_twilight_end: string;
            /** The start of astronomical twilight in the evening */
            astronomical_twilight_begin: string;
            /** The end of astronomical twilight in the evening */
            astronomical_twilight_end: string;
        }
    }
}
