// This file was auto-generated by Fern from our API Definition.

/**
 * Wrapper object containing one WHOIS result or error per requested domain, in request order.
 */
export interface BulkDomainWhoisLookupV2Response {
    /** Array of per-domain results, one entry per requested domain. Each entry is either a full WHOIS result or, if that domain could not be resolved, an error object. */
    bulk_whois_response: BulkDomainWhoisLookupV2Response.BulkWhoisResponse.Item[];
}

export namespace BulkDomainWhoisLookupV2Response {
    export type BulkWhoisResponse = BulkWhoisResponse.Item[];

    export namespace BulkWhoisResponse {
        export type Item =
            /**
             * Current WHOIS registration record for one successfully resolved domain. */
            | {
                  status: boolean;
                  domain_name: string;
                  query_time: string;
                  whois_server?: string | undefined;
                  domain_registered: "yes" | "no" | "restricted";
                  secure_dns?: boolean | undefined;
                  domain_handle?: string | undefined;
                  create_date?: string | undefined;
                  update_date?: string | undefined;
                  expiry_date?: string | undefined;
                  domain_registrar?:
                      | {
                            iana_id?: string | undefined;
                            id?: string | undefined;
                            id_type?: string | undefined;
                            handle?: string | undefined;
                            registry_id?: string | undefined;
                            authoritative_registry_name?: string | undefined;
                            organization_number?: string | undefined;
                            is_sponsor?: boolean | undefined;
                            status?: string | undefined;
                            registrar_name?: string | undefined;
                            normalized_name?: string | undefined;
                            whois_server?: string | undefined;
                            rdap_server?: string | undefined;
                            website_url?: string | undefined;
                            email_address?: string | undefined;
                            phone_number?: string | undefined;
                        }
                      | undefined;
                  reseller_contact?:
                      | {
                            name?: string | undefined;
                            company?: string | undefined;
                            street?: string | undefined;
                            city?: string | undefined;
                            state?: string | undefined;
                            zip_code?: string | undefined;
                            country_name?: string | undefined;
                            country_code?: string | undefined;
                            email_address?: string | undefined;
                            phone?: string | undefined;
                            fax?: string | undefined;
                            mailing_address?: string | undefined;
                        }
                      | undefined;
                  registrant_contact?:
                      | {
                            id?: string | undefined;
                            name?: string | undefined;
                            company?: string | undefined;
                            street?: string | undefined;
                            city?: string | undefined;
                            state?: string | undefined;
                            zip_code?: string | undefined;
                            country_name?: string | undefined;
                            country_code?: string | undefined;
                            email_address?: string | undefined;
                            phone?: string | undefined;
                            fax?: string | undefined;
                            mailing_address?: string | undefined;
                        }
                      | undefined;
                  administrative_contact?:
                      | {
                            id?: string | undefined;
                            name?: string | undefined;
                            company?: string | undefined;
                            street?: string | undefined;
                            city?: string | undefined;
                            state?: string | undefined;
                            zip_code?: string | undefined;
                            country_name?: string | undefined;
                            country_code?: string | undefined;
                            email_address?: string | undefined;
                            phone?: string | undefined;
                            fax?: string | undefined;
                            mailing_address?: string | undefined;
                        }
                      | undefined;
                  technical_contact?:
                      | {
                            id?: string | undefined;
                            name?: string | undefined;
                            company?: string | undefined;
                            street?: string | undefined;
                            city?: string | undefined;
                            state?: string | undefined;
                            zip_code?: string | undefined;
                            country_name?: string | undefined;
                            country_code?: string | undefined;
                            email_address?: string | undefined;
                            phone?: string | undefined;
                            fax?: string | undefined;
                            mailing_address?: string | undefined;
                        }
                      | undefined;
                  billing_contact?:
                      | {
                            name?: string | undefined;
                            company?: string | undefined;
                            street?: string | undefined;
                            city?: string | undefined;
                            state?: string | undefined;
                            zip_code?: string | undefined;
                            country_name?: string | undefined;
                            country_code?: string | undefined;
                            email_address?: string | undefined;
                            phone?: string | undefined;
                            fax?: string | undefined;
                            mailing_address?: string | undefined;
                        }
                      | undefined;
                  abuse_contact?:
                      | {
                            registrar_name?: string | undefined;
                            email_address?: string | undefined;
                            phone_number?: string | undefined;
                        }
                      | undefined;
                  eligibility_info?:
                      | {
                            id?: string | undefined;
                            name?: string | undefined;
                            type?: string | undefined;
                        }
                      | undefined;
                  name_servers?: string[] | undefined;
                  domain_status?: string[] | undefined;
                  whois_raw_domain?: string | undefined;
                  registry_data?:
                      | {
                            domain_name?: string | undefined;
                            query_time?: string | undefined;
                            whois_server?: string | undefined;
                            domain_registered?: ("yes" | "no" | "restricted") | undefined;
                            create_date?: string | undefined;
                            update_date?: string | undefined;
                            expiry_date?: string | undefined;
                            name_servers?: string[] | undefined;
                            domain_status?: string[] | undefined;
                            whois_raw_registery?: string | undefined;
                            domain_registrar?:
                                | {
                                      iana_id?: string | undefined;
                                      id?: string | undefined;
                                      id_type?: string | undefined;
                                      handle?: string | undefined;
                                      registry_id?: string | undefined;
                                      authoritative_registry_name?: string | undefined;
                                      organization_number?: string | undefined;
                                      is_sponsor?: boolean | undefined;
                                      status?: string | undefined;
                                      registrar_name?: string | undefined;
                                      normalized_name?: string | undefined;
                                      whois_server?: string | undefined;
                                      rdap_server?: string | undefined;
                                      website_url?: string | undefined;
                                      email_address?: string | undefined;
                                      phone_number?: string | undefined;
                                  }
                                | undefined;
                        }
                      | undefined;
              }
            /**
             * Per-item error, returned in place of a WHOIS result when an individual domain's extension is unsupported or its lookup otherwise fails. */
            | {
                  status: boolean;
                  domain_name: string;
                  status_code: number;
                  error?: string | undefined;
                  message: string;
              };
    }
}
