// This file was auto-generated by Fern from our API Definition.

export const BulkDomainWhoisLookupRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type BulkDomainWhoisLookupRequestFormat =
    (typeof BulkDomainWhoisLookupRequestFormat)[keyof typeof BulkDomainWhoisLookupRequestFormat];
