// This file was auto-generated by Fern from our API Definition.

export const BulkUserAgentLookupRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type BulkUserAgentLookupRequestFormat =
    (typeof BulkUserAgentLookupRequestFormat)[keyof typeof BulkUserAgentLookupRequestFormat];
