// This file was auto-generated by Fern from our API Definition.

export const BulkScreenshotCaptureRequestFormat = {
    Json: "json",
} as const;
export type BulkScreenshotCaptureRequestFormat =
    (typeof BulkScreenshotCaptureRequestFormat)[keyof typeof BulkScreenshotCaptureRequestFormat];
