// This file was auto-generated by Fern from our API Definition.

export const BulkCurrentWeatherRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type BulkCurrentWeatherRequestFormat =
    (typeof BulkCurrentWeatherRequestFormat)[keyof typeof BulkCurrentWeatherRequestFormat];
