// This file was auto-generated by Fern from our API Definition.

export const BulkDomainDnsLookupRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type BulkDomainDnsLookupRequestFormat =
    (typeof BulkDomainDnsLookupRequestFormat)[keyof typeof BulkDomainDnsLookupRequestFormat];
