// This file was auto-generated by Fern from our API Definition.

export const BulkPhoneValidateRequestFormat = {
    Json: "json",
} as const;
export type BulkPhoneValidateRequestFormat =
    (typeof BulkPhoneValidateRequestFormat)[keyof typeof BulkPhoneValidateRequestFormat];
