// This file was auto-generated by Fern from our API Definition.

export const BulkDomainAvailabilityCheckRequestSource = {
    Dns: "dns",
    Whois: "whois",
} as const;
export type BulkDomainAvailabilityCheckRequestSource =
    (typeof BulkDomainAvailabilityCheckRequestSource)[keyof typeof BulkDomainAvailabilityCheckRequestSource];
