// This file was auto-generated by Fern from our API Definition.

export const BulkVatRateByCountryRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type BulkVatRateByCountryRequestFormat =
    (typeof BulkVatRateByCountryRequestFormat)[keyof typeof BulkVatRateByCountryRequestFormat];
