// This file was auto-generated by Fern from our API Definition.

export const BulkGeolocationLookupV2RequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type BulkGeolocationLookupV2RequestFormat =
    (typeof BulkGeolocationLookupV2RequestFormat)[keyof typeof BulkGeolocationLookupV2RequestFormat];
