// This file was auto-generated by Fern from our API Definition.

export const BulkZipcodeLookupRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type BulkZipcodeLookupRequestFormat =
    (typeof BulkZipcodeLookupRequestFormat)[keyof typeof BulkZipcodeLookupRequestFormat];
