// This file was auto-generated by Fern from our API Definition.

export const BulkDomainAvailabilityCheckRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type BulkDomainAvailabilityCheckRequestFormat =
    (typeof BulkDomainAvailabilityCheckRequestFormat)[keyof typeof BulkDomainAvailabilityCheckRequestFormat];
