// This file was auto-generated by Fern from our API Definition.

export const BulkEmailValidateRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type BulkEmailValidateRequestFormat =
    (typeof BulkEmailValidateRequestFormat)[keyof typeof BulkEmailValidateRequestFormat];
