// This file was auto-generated by Fern from our API Definition.

export const BulkGeolocationLookupRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type BulkGeolocationLookupRequestFormat =
    (typeof BulkGeolocationLookupRequestFormat)[keyof typeof BulkGeolocationLookupRequestFormat];
