// This file was auto-generated by Fern from our API Definition.

export interface BulkDomainDnsLookupResponse {
    bulk_dns_info: BulkDomainDnsLookupResponse.BulkDnsInfo.Item[];
}

export namespace BulkDomainDnsLookupResponse {
    export type BulkDnsInfo = BulkDnsInfo.Item[];

    export namespace BulkDnsInfo {
        export interface Item {
            /** Indicates whether the query was processed successfully. */
            status: boolean;
            /** Timestamp when the query was executed (format YYYY-MM-DD HH:mm:ss, not ISO 8601). */
            queryTime: string;
            /** Queried domain. Absent when this result is for a queried IP address instead (see `ipAddress`). */
            domainName?: string | undefined;
            /** Indicates whether the domain is registered. Absent when this result is for a queried IP address instead. */
            domainRegistered?: boolean | undefined;
            /** Queried IP address, present when this result is for reverse DNS (PTR) enrichment instead of a domain name. */
            ipAddress?: string | undefined;
            dnsTypes: Item.DnsTypes;
            /** List of DNS records, each based on its type. */
            dnsRecords: Item.DnsRecords.Item[];
        }

        export namespace Item {
            export interface DnsTypes {
                A?: number | undefined;
                AAAA?: number | undefined;
                CNAME?: number | undefined;
                MX?: number | undefined;
                NS?: number | undefined;
                SOA?: number | undefined;
                TXT?: number | undefined;
                SPF?: number | undefined;
            }

            export type DnsRecords = DnsRecords.Item[];

            export namespace DnsRecords {
                export type Item =
                    | {
                          name: string;
                          type: number;
                          dnsType: "A" | "AAAA";
                          ttl: number;
                          rawText: string;
                          rRsetType: number;
                          address: string;
                      }
                    | {
                          name: string;
                          type: number;
                          dnsType: "CNAME";
                          ttl: number;
                          rawText: string;
                          rRsetType: number;
                          target: string;
                      }
                    | {
                          name: string;
                          type: number;
                          dnsType: "MX";
                          ttl: number;
                          rawText: string;
                          rRsetType: number;
                          target: string;
                          priority: number;
                      }
                    | {
                          name: string;
                          type: number;
                          dnsType: "NS";
                          ttl: number;
                          rawText: string;
                          rRsetType: number;
                          singleName: string;
                      }
                    | {
                          name: string;
                          type: number;
                          dnsType: "SOA";
                          ttl: number;
                          rawText: string;
                          rRsetType: number;
                          admin: string;
                          host: string;
                          expire: number;
                          minimum: number;
                          refresh: number;
                          retry: number;
                          serial: number;
                      }
                    | {
                          name: string;
                          type: number;
                          dnsType: "TXT" | "SPF";
                          ttl: number;
                          rawText: string;
                          rRsetType: number;
                          strings: string[];
                      };
            }
        }
    }
}
