// This file was auto-generated by Fern from our API Definition.

export const BulkDomainWhoisLookupV2RequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type BulkDomainWhoisLookupV2RequestFormat =
    (typeof BulkDomainWhoisLookupV2RequestFormat)[keyof typeof BulkDomainWhoisLookupV2RequestFormat];
