// This file was auto-generated by Fern from our API Definition.

export interface BulkUserAgentLookupResponseItem {
    /** User-agent string that is parsed for browser, device and operating system details. */
    user_agent_string: string;
    /** Agent name or the actual browser name that was used. */
    name: string;
    /**
     * Agent type or the browser type that was used. Possible values:
     * 1. Browser
     * 2. Browser Webview
     * 3. Mobile App
     * 4. Robot Mobile
     * 5. Cloud Application
     * 6. Email Client
     * 7. Voice
     * 8. Special
     * 9. Testclient
     * 10. Hacker
     * 11. Unknown
     */
    type: string;
    /** Agent version or the browser version */
    version: string;
    /** Agent version major or the browser version major */
    version_major: string;
    device: BulkUserAgentLookupResponseItem.Device;
    engine: BulkUserAgentLookupResponseItem.Engine;
    operating_system: BulkUserAgentLookupResponseItem.OperatingSystem;
    /** Error message for this user-agent string, present only if parsing of this entry failed. */
    message?: string | undefined;
}

export namespace BulkUserAgentLookupResponseItem {
    export interface Device {
        /** Device name or the hardware that was used */
        name: string;
        /**
         * Device type or the hardware type. Possible values:
         * 1. Desktop
         * 2. Mobile
         * 3. Tablet
         * 4. Phone
         * 5. Watch
         * 6. Virtual Reality
         * 7. eReader
         * 8. Set-top box
         * 9. TV
         * 10. Game Console
         * 11. Handheld Game Console
         * 12. Voice
         * 13. Robot
         * 14. Robot Mobile
         * 15. Robot Imitator
         * 16. Hacker
         * 17. Anonymized
         * 18. Unknown
         */
        type: string;
        /** Device brand or the hardware brand name */
        brand: string;
        /** Device's CPU model or machine CPU */
        cpu: string;
    }

    export interface Engine {
        /** Layout engine name or the underlying core that converts the HTML into visual */
        name: string;
        /**
         * Layout engine type. Possible values:
         * 1. Browser
         * 2. Mobile App
         * 3. Hacker
         * 4. Robot
         * 5. Unknown
         */
        type: string;
        /** Layout engine version */
        version: string;
        /** Layout engine version major */
        version_major: string;
    }

    export interface OperatingSystem {
        /** Operating system name or the base software name that runs on the hardware. */
        name: string;
        /**
         * Operating system type. Possible values:
         * 1. Desktop
         * 2. Mobile
         * 3. Game Console
         * 4. Embedded
         * 5. Cloud
         * 6. Hacker
         * 7. Anonymized
         * 8. Unknown
         */
        type: string;
        /** Operating system version */
        version: string;
        /** Operating system version major */
        version_major: string;
        /** Operating system build */
        build: string;
    }
}
