// This file was auto-generated by Fern from our API Definition.

export interface BulkDomainAvailabilityCheckResponse {
    bulk_domain_available_response: BulkDomainAvailabilityCheckResponse.BulkDomainAvailableResponse.Item[];
}

export namespace BulkDomainAvailabilityCheckResponse {
    export type BulkDomainAvailableResponse = BulkDomainAvailableResponse.Item[];

    export namespace BulkDomainAvailableResponse {
        export interface Item {
            domain: string;
            domainAvailability: boolean;
            status: boolean;
        }
    }
}
