// This file was auto-generated by Fern from our API Definition.

export type BulkGeolocationLookupV2ResponseItem =
    /**
     * Geolocation and threat intelligence result for one successfully resolved IP address. */
    | {
          ip: string;
          domain?: string | undefined;
          hostname?: string | undefined;
          location?:
              | {
                    continent_code: string;
                    continent_name: string;
                    country_code2: string;
                    country_code3: string;
                    country_name: string;
                    country_name_official: string;
                    country_capital: string;
                    state_prov?: string | undefined;
                    state_code?: string | undefined;
                    district?: string | undefined;
                    city?: string | undefined;
                    locality?: string | undefined;
                    accuracy_radius?: string | undefined;
                    confidence?: string | undefined;
                    dma_code?: (string | null) | undefined;
                    zipcode?: string | undefined;
                    latitude: string;
                    longitude: string;
                    is_eu: boolean;
                    country_flag: string;
                    geoname_id?: string | undefined;
                    country_emoji?: string | undefined;
                }
              | undefined;
          country_metadata?:
              | {
                    calling_code: string;
                    tld: string;
                    languages: string[];
                }
              | undefined;
          network?:
              | {
                    connection_type?: string | undefined;
                    route?: string | undefined;
                    is_anycast?: boolean | undefined;
                }
              | undefined;
          asn?:
              | {
                    as_number?: string | undefined;
                    organization?: string | undefined;
                    country?: string | undefined;
                    type?: string | undefined;
                    domain?: string | undefined;
                    date_allocated?: string | undefined;
                    rir?: string | undefined;
                }
              | undefined;
          company?:
              | {
                    name?: string | undefined;
                    type?: string | undefined;
                    domain?: string | undefined;
                }
              | undefined;
          currency?:
              | {
                    code?: string | undefined;
                    name?: string | undefined;
                    symbol?: string | undefined;
                }
              | undefined;
          security?:
              | {
                    threat_score: number;
                    is_tor: boolean;
                    is_proxy: boolean;
                    proxy_provider_names?: string[] | undefined;
                    proxy_confidence_score: number;
                    proxy_last_seen?: string | undefined;
                    is_residential_proxy: boolean;
                    is_vpn: boolean;
                    vpn_provider_names?: string[] | undefined;
                    vpn_confidence_score: number;
                    vpn_last_seen?: string | undefined;
                    is_relay: boolean;
                    relay_provider_name?: string | undefined;
                    is_anonymous: boolean;
                    is_known_attacker: boolean;
                    is_bot: boolean;
                    is_spam: boolean;
                    is_cloud_provider: boolean;
                    cloud_provider_name?: string | undefined;
                }
              | undefined;
          abuse?:
              | {
                    route?: string | undefined;
                    country?: string | undefined;
                    name?: string | undefined;
                    organization?: string | undefined;
                    kind?: string | undefined;
                    address?: string | undefined;
                    emails?: string[] | undefined;
                    phone_numbers?: string[] | undefined;
                }
              | undefined;
          time_zone?:
              | {
                    name: string;
                    offset: number;
                    offset_with_dst: number;
                    current_time: string;
                    current_time_unix: number;
                    current_tz_abbreviation?: string | undefined;
                    current_tz_full_name?: string | undefined;
                    standard_tz_abbreviation?: string | undefined;
                    standard_tz_full_name?: string | undefined;
                    is_dst: boolean;
                    dst_savings: number;
                    dst_exists: boolean;
                    dst_tz_abbreviation?: string | undefined;
                    dst_tz_full_name?: string | undefined;
                    dst_start?:
                        | {
                              utc_time?: string | undefined;
                              duration?: string | undefined;
                              gap?: boolean | undefined;
                              date_time_after?: string | undefined;
                              date_time_before?: string | undefined;
                              overlap?: boolean | undefined;
                          }
                        | undefined;
                    dst_end?:
                        | {
                              utc_time?: string | undefined;
                              duration?: string | undefined;
                              gap?: boolean | undefined;
                              date_time_after?: string | undefined;
                              date_time_before?: string | undefined;
                              overlap?: boolean | undefined;
                          }
                        | undefined;
                }
              | undefined;
          user_agent?:
              | {
                    user_agent_string?: string | undefined;
                    name?: string | undefined;
                    type?: string | undefined;
                    version?: string | undefined;
                    version_major?: string | undefined;
                    device?:
                        | {
                              name?: string | undefined;
                              type?: string | undefined;
                              brand?: string | undefined;
                              cpu?: string | undefined;
                          }
                        | undefined;
                    engine?:
                        | {
                              name?: string | undefined;
                              type?: string | undefined;
                              version?: string | undefined;
                              version_major?: string | undefined;
                          }
                        | undefined;
                    operating_system?:
                        | {
                              name?: string | undefined;
                              type?: string | undefined;
                              version?: string | undefined;
                              version_major?: string | undefined;
                              build?: string | undefined;
                          }
                        | undefined;
                }
              | undefined;
      }
    /**
     * Per-item error, returned in place of a location result when an individual IP is invalid, bogon/reserved, or not found in the database. */
    | {
          message: string;
      };
