// This file was auto-generated by Fern from our API Definition.

export interface BulkEmailValidateResponse {
    /** Array of SingleEmailValidationResponse objects for bulk validation */
    emailValidationResponses?: BulkEmailValidateResponse.EmailValidationResponses.Item[] | undefined;
}

export namespace BulkEmailValidateResponse {
    export type EmailValidationResponses = EmailValidationResponses.Item[];

    export namespace EmailValidationResponses {
        export interface Item {
            success: boolean;
            email: string;
            name?: string | undefined;
            reason?: string | undefined;
            validEmail: Item.ValidEmail;
            validSyntax: boolean;
            domain: Item.Domain;
            account: Item.Account;
            dns: Item.Dns;
            ipAddress?: string | undefined;
            address?: Item.Address | undefined;
        }

        export namespace Item {
            export const ValidEmail = {
                Valid: "valid",
                Invalid: "Invalid",
                Unknown: "Unknown",
                Risky: "Risky",
            } as const;
            export type ValidEmail = (typeof ValidEmail)[keyof typeof ValidEmail];

            export interface Domain {
                name: string;
                disposable: boolean;
                spam: boolean;
                free: boolean;
                catchAll: boolean;
                validDomain: boolean;
            }

            export interface Account {
                role: boolean;
                fullMailBox?: boolean | undefined;
            }

            export interface Dns {
                mxRecords: string[];
                /** Collection of A (Address) records for the domain. */
                aRecords: string[];
            }

            export interface Address {
                security?: Address.Security | undefined;
                location?: Address.Location | undefined;
                validIpAddress?: boolean | undefined;
            }

            export namespace Address {
                export interface Security {
                    threat_score: number;
                    is_tor: boolean;
                    is_proxy: boolean;
                    proxy_type: string;
                    proxy_provider: string;
                    is_anonymous: boolean;
                    is_known_attacker: boolean;
                    is_spam: boolean;
                    is_bot: boolean;
                    is_cloud_provider: boolean;
                    cloud_provider: string;
                }

                export interface Location {
                    city?: string | undefined;
                    district?: string | undefined;
                    confidence?: string | undefined;
                    zipcode?: string | undefined;
                    state_prov?: string | undefined;
                    country_name?: string | undefined;
                    continent_name?: string | undefined;
                    continent_code?: string | undefined;
                    country_code2?: string | undefined;
                    country_code3?: string | undefined;
                    country_name_official?: string | undefined;
                    accuracy_radius?: string | undefined;
                    is_eu?: boolean | undefined;
                }
            }
        }
    }
}
