// This file was auto-generated by Fern from our API Definition.

export interface BulkZipcodeLookupResponse {
    results?: BulkZipcodeLookupResponse.Results.Item[] | undefined;
}

export namespace BulkZipcodeLookupResponse {
    export type Results = Results.Item[];

    export namespace Results {
        export interface Item {
            code?: string | undefined;
            country_code?: string | undefined;
            region?: string | undefined;
            city?: string | undefined;
            locality?: string | undefined;
            latitude?: number | undefined;
            longitude?: number | undefined;
        }
    }
}
