// This file was auto-generated by Fern from our API Definition.

export interface BulkVatRateByCountryResponse {
    countries: BulkVatRateByCountryResponse.Countries.Item[];
}

export namespace BulkVatRateByCountryResponse {
    export type Countries = Countries.Item[];

    export namespace Countries {
        export interface Item {
            /** Country identifier in Alpha-2 (US), Alpha-3 (USA), or full name (United_States). Case-insensitive and may use underscores. */
            country: string;
            /** Optional state identifier in Alpha-2 (NY) or full name (New_York). Required only for state-level taxation. Case-insensitive and may use underscores. */
            state?: string | undefined;
            /** Tax type applied for the country or state. Possible values include vat or none. */
            type?: string | undefined;
            /** ISO 4217 currency code. */
            currency?: string | undefined;
            /** Standard VAT or sales tax rate. Zero indicates no tax. */
            standard_rate?: number | undefined;
            /** Optional reduced VAT rates applicable in the country. */
            reduced_rate?: number[] | undefined;
            /** Optional super-reduced VAT rates applicable in specific categories. */
            super_reduced_rate?: number[] | undefined;
            parking_rate?: number | undefined;
            /** Optional category-wise VAT rates. */
            categories?: Record<string, number> | undefined;
        }
    }
}
