// This file was auto-generated by Fern from our API Definition.

export const BulkIpSecurityLookupRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type BulkIpSecurityLookupRequestFormat =
    (typeof BulkIpSecurityLookupRequestFormat)[keyof typeof BulkIpSecurityLookupRequestFormat];
