// This file was auto-generated by Fern from our API Definition.

export const CommodityLatestRatesRequestUpdates = {
    TenM: "10m",
    OneM: "1m",
} as const;
export type CommodityLatestRatesRequestUpdates =
    (typeof CommodityLatestRatesRequestUpdates)[keyof typeof CommodityLatestRatesRequestUpdates];
