// This file was auto-generated by Fern from our API Definition.

export interface CommodityHistoricalRatesV2Response {
    /** API request success indicator. "true" for successful requests. */
    success: boolean;
    /** Date for which the user requested the commodity price. Format: YYYY-MM-DD. */
    date: string;
    /** Map of requested commodity symbols to their OHLC price data on the given date. */
    rates: Record<string, CommodityHistoricalRatesV2Response.Rates.Value>;
}

export namespace CommodityHistoricalRatesV2Response {
    export namespace Rates {
        export interface Value {
            /** Date for which prices were fetched (YYYY-MM-DD). May differ from the requested date when the API falls back to the last available rate before it, or snaps to the first day of the month for monthly-updated commodities. */
            date: string;
            /** Opening price on the given date. 0 for monthly-updated commodities. */
            open: number;
            /** Highest price recorded on the given date. 0 for monthly-updated commodities. */
            high: number;
            /** Lowest price recorded on the given date. 0 for monthly-updated commodities. */
            low: number;
            /** Closing price on the given date. */
            close: number;
        }
    }
}
