// This file was auto-generated by Fern from our API Definition.

export const CommodityTimeSeriesV2RequestFormat = {
    Json: "json",
} as const;
export type CommodityTimeSeriesV2RequestFormat =
    (typeof CommodityTimeSeriesV2RequestFormat)[keyof typeof CommodityTimeSeriesV2RequestFormat];
