// This file was auto-generated by Fern from our API Definition.

export const CommodityLatestRatesRequestFormat = {
    Json: "json",
} as const;
export type CommodityLatestRatesRequestFormat =
    (typeof CommodityLatestRatesRequestFormat)[keyof typeof CommodityLatestRatesRequestFormat];
