// This file was auto-generated by Fern from our API Definition.

export const CommoditySymbolsV2RequestFormat = {
    Json: "json",
} as const;
export type CommoditySymbolsV2RequestFormat =
    (typeof CommoditySymbolsV2RequestFormat)[keyof typeof CommoditySymbolsV2RequestFormat];
