// This file was auto-generated by Fern from our API Definition.

export const CommodityHistoricalRatesRequestFormat = {
    Json: "json",
} as const;
export type CommodityHistoricalRatesRequestFormat =
    (typeof CommodityHistoricalRatesRequestFormat)[keyof typeof CommodityHistoricalRatesRequestFormat];
