// This file was auto-generated by Fern from our API Definition.

export interface CommodityHistoricalRatesResponse {
    /** API request success indicator. "true" for successful requests. */
    success: boolean;
    /** Unix timestamp indicating when the response was generated. */
    timestamp: number;
    /** Map containing rate data for all the requested commodities. */
    rates: Record<string, number>;
    /** Map containing detailed information for all the requested commodities keyed by commodity symbol. */
    metadata: Record<string, CommodityHistoricalRatesResponse.Metadata.Value>;
}

export namespace CommodityHistoricalRatesResponse {
    export namespace Metadata {
        export interface Value {
            /** Unit of the respective commodity. */
            unit: string;
            /** Quote currency of the respective commodity. */
            quote: string;
        }
    }
}
