// This file was auto-generated by Fern from our API Definition.

export const CommodityLatestRatesV2RequestFormat = {
    Json: "json",
} as const;
export type CommodityLatestRatesV2RequestFormat =
    (typeof CommodityLatestRatesV2RequestFormat)[keyof typeof CommodityLatestRatesV2RequestFormat];
