// This file was auto-generated by Fern from our API Definition.

export const CommodityFluctuationV2RequestFormat = {
    Json: "json",
} as const;
export type CommodityFluctuationV2RequestFormat =
    (typeof CommodityFluctuationV2RequestFormat)[keyof typeof CommodityFluctuationV2RequestFormat];
