// This file was auto-generated by Fern from our API Definition.

export interface CommodityLatestRatesV2Response {
    /** API request success indicator. "true" for successful requests. */
    success: boolean;
    /** Unix timestamp (seconds) indicating when the response was generated. */
    timestamp: number;
    /** Map of requested commodity symbols to their current live price. */
    rates: Record<string, number>;
    /** Map containing unit and quote currency metadata for all requested commodities, keyed by commodity symbol. */
    metadata: Record<string, CommodityLatestRatesV2Response.Metadata.Value>;
    /** Present only when currency conversion for the requested `quote` is temporarily unavailable; rates are returned in each commodity's default currency instead. */
    warning?: string | undefined;
}

export namespace CommodityLatestRatesV2Response {
    export namespace Metadata {
        export interface Value {
            /** Unit of measurement for the commodity (e.g., Bbl, T.oz). */
            unit: string;
            /** Quote currency used for this commodity's price. */
            quote: string;
        }
    }
}
