// This file was auto-generated by Fern from our API Definition.

export const CommodityHistoricalRatesV2RequestFormat = {
    Json: "json",
} as const;
export type CommodityHistoricalRatesV2RequestFormat =
    (typeof CommodityHistoricalRatesV2RequestFormat)[keyof typeof CommodityHistoricalRatesV2RequestFormat];
