// This file was auto-generated by Fern from our API Definition.

export interface CommoditySymbolsV2Response {
    /** API request success indicator. "true" for successful requests. */
    success: boolean;
    /** An array of commodity symbol objects. */
    symbols: CommoditySymbolsV2Response.Symbols.Item[];
}

export namespace CommoditySymbolsV2Response {
    export type Symbols = Symbols.Item[];

    export namespace Symbols {
        export interface Item {
            /** Unique identifier/ticker symbol for the commodity (e.g., XAU, NG-FUT). Use this value in the symbols parameter of the rate endpoints. */
            symbol: string;
            /** Full name of the commodity (e.g., Gold, Natural Gas Futures). */
            name: string;
            /** Short description of the commodity. May be an empty string for some symbols. */
            description?: string | undefined;
            /** Category the commodity belongs to (e.g., Metals, Energy, Agriculture, Industrial, Raw Materials, Oils and Meals, Textiles, Meats, Poultry, Livestock). */
            category: string;
            /** Current status of the commodity. "inactive" means the symbol is deprecated - latest rates are unavailable, but historical rates remain available up to its deprecationDate. */
            status: Item.Status;
            /** The rate at which this commodity's price is updated. */
            updateInterval: Item.UpdateInterval;
            /** Data source for the symbol (e.g., World Bank). Present only for some symbols. */
            exchange?: string | undefined;
            /** Present only when status is "inactive". Date the symbol was deprecated (YYYY-MM-DD). */
            deprecationDate?: string | undefined;
            currency: Item.Currency;
            unit: Item.Unit;
        }

        export namespace Item {
            /** Current status of the commodity. "inactive" means the symbol is deprecated - latest rates are unavailable, but historical rates remain available up to its deprecationDate. */
            export const Status = {
                Active: "active",
                Inactive: "inactive",
            } as const;
            export type Status = (typeof Status)[keyof typeof Status];
            /** The rate at which this commodity's price is updated. */
            export const UpdateInterval = {
                PerSecond: "PER_SECOND",
                PerMinute: "PER_MINUTE",
                Per10Minutes: "PER_10_MINUTES",
                PerHour: "PER_HOUR",
                PerDay: "PER_DAY",
                PerWeek: "PER_WEEK",
                PerMonth: "PER_MONTH",
            } as const;
            export type UpdateInterval = (typeof UpdateInterval)[keyof typeof UpdateInterval];

            export interface Currency {
                /** The ISO 4217 currency code (e.g., "USD"). */
                code: string;
                /** The full name of the currency (e.g., "US Dollar"). */
                name: string;
                /** The symbol of the currency (e.g., "$"). */
                symbol: string;
            }

            export interface Unit {
                /** The abbreviated unit symbol (e.g., "T.oz", "MMBtu"). */
                symbol: string;
                /** The full name of the unit of measurement. */
                name: string;
            }
        }
    }
}
