// This file was auto-generated by Fern from our API Definition.

export const CommodityFluctuationRequestFormat = {
    Json: "json",
} as const;
export type CommodityFluctuationRequestFormat =
    (typeof CommodityFluctuationRequestFormat)[keyof typeof CommodityFluctuationRequestFormat];
