// This file was auto-generated by Fern from our API Definition.

export interface CommodityTimeSeriesV2Response {
    /** API request success indicator. "true" for successful requests. */
    success: boolean;
    /** The start date of the time series data in YYYY-MM-DD format. */
    startDate: string;
    /** The end date of the time series data in YYYY-MM-DD format. */
    endDate: string;
    /** Map of trading dates (YYYY-MM-DD) to per-symbol OHLC data. Non-trading days are excluded. */
    rates: Record<string, Record<string, CommodityTimeSeriesV2Response.Rates.Value>>;
}

export namespace CommodityTimeSeriesV2Response {
    export namespace Rates {
        export interface Value {
            /** Opening price on the given date. 0 for monthly-updated commodities. */
            open: number;
            /** Highest price on the given date. 0 for monthly-updated commodities. */
            high: number;
            /** Lowest price on the given date. 0 for monthly-updated commodities. */
            low: number;
            /** Closing price on the given date. */
            close: number;
        }
    }
}
