// This file was auto-generated by Fern from our API Definition.

export const CommodityTimeSeriesRequestFormat = {
    Json: "json",
} as const;
export type CommodityTimeSeriesRequestFormat =
    (typeof CommodityTimeSeriesRequestFormat)[keyof typeof CommodityTimeSeriesRequestFormat];
