// This file was auto-generated by Fern from our API Definition.

export interface CommodityFluctuationV2Response {
    /** API request success indicator. "true" for successful requests. */
    success: boolean;
    /** The start date of the fluctuation interval in YYYY-MM-DD format. */
    startDate: string;
    /** The end date of the fluctuation interval in YYYY-MM-DD format. */
    endDate: string;
    /** Map keyed by commodity symbol; value contains fluctuation metrics. */
    rates: Record<string, CommodityFluctuationV2Response.Rates.Value>;
}

export namespace CommodityFluctuationV2Response {
    export namespace Rates {
        export interface Value {
            /** Price of the commodity on the start date. */
            startRate: number;
            /** Price of the commodity on the end date. */
            endRate: number;
            /** Absolute price difference between end and start dates. May be negative. */
            change: number;
            /** Percentage price change from start to end date. May be negative. */
            changePercent: number;
        }
    }
}
