// This file was auto-generated by Fern from our API Definition.

export const CommoditySymbolsRequestFormat = {
    Json: "json",
} as const;
export type CommoditySymbolsRequestFormat =
    (typeof CommoditySymbolsRequestFormat)[keyof typeof CommoditySymbolsRequestFormat];
