// This file was auto-generated by Fern from our API Definition.

export interface CommoditySymbolsResponse {
    /** Indicates whether the API request was successful. */
    success: boolean;
    /** An array of commodity symbol objects. */
    symbols: CommoditySymbolsResponse.Symbols.Item[];
}

export namespace CommoditySymbolsResponse {
    export type Symbols = Symbols.Item[];

    export namespace Symbols {
        export interface Item {
            /** The unique ticker symbol for the commodity (e.g., "XAU", "NG-FUT"). */
            symbol: string;
            /** The full name of the commodity (e.g., "Gold", "Natural Gas Futures"). */
            name: string;
            /** The category the commodity belongs to (e.g., "Metals", "Energy"). */
            category: string;
            /** The current status of the commodity. Possible value: "active". */
            status: string;
            /** The rate at which this commodity's price is updated. */
            updateInterval: Item.UpdateInterval;
            currency: Item.Currency;
            unit: Item.Unit;
        }

        export namespace Item {
            /** The rate at which this commodity's price is updated. */
            export const UpdateInterval = {
                PerSecond: "PER_SECOND",
                PerMinute: "PER_MINUTE",
            } as const;
            export type UpdateInterval = (typeof UpdateInterval)[keyof typeof UpdateInterval];

            export interface Currency {
                /** The ISO 4217 currency code (e.g., "USD"). */
                code: string;
                /** The full name of the currency (e.g., "US Dollar"). */
                name: string;
                /** The symbol of the currency (e.g., "$"). */
                symbol: string;
            }

            export interface Unit {
                /** The abbreviated unit symbol (e.g., "T.oz", "MMBtu"). */
                symbol: string;
                /** The full name of the unit of measurement. */
                name: string;
            }
        }
    }
}
