// This file was auto-generated by Fern from our API Definition.

export const CurrencySymbolsRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type CurrencySymbolsRequestFormat =
    (typeof CurrencySymbolsRequestFormat)[keyof typeof CurrencySymbolsRequestFormat];
