// This file was auto-generated by Fern from our API Definition.

export interface CurrencySupportedResponse {
    /** A map of all supported currencies, keyed by currency code. */
    supportedCurrenciesMap: Record<string, CurrencySupportedResponse.SupportedCurrenciesMap.Value>;
}

export namespace CurrencySupportedResponse {
    export namespace SupportedCurrenciesMap {
        export interface Value {
            currencyCode: string;
            currencyName: string;
            countryCode: string;
            countryName: string;
            status: Value.Status;
            availableFrom: string;
            availableUntil: string;
            icon: string;
        }

        export namespace Value {
            export const Status = {
                Available: "AVAILABLE",
                Depreciated: "DEPRECIATED",
            } as const;
            export type Status = (typeof Status)[keyof typeof Status];
        }
    }
}
