// This file was auto-generated by Fern from our API Definition.

export const CurrencyLatestRatesRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type CurrencyLatestRatesRequestFormat =
    (typeof CurrencyLatestRatesRequestFormat)[keyof typeof CurrencyLatestRatesRequestFormat];
