// This file was auto-generated by Fern from our API Definition.

export const CurrencyConvertHistoricalRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type CurrencyConvertHistoricalRequestFormat =
    (typeof CurrencyConvertHistoricalRequestFormat)[keyof typeof CurrencyConvertHistoricalRequestFormat];
