// This file was auto-generated by Fern from our API Definition.

export const CurrencyHistoricalRatesRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type CurrencyHistoricalRatesRequestFormat =
    (typeof CurrencyHistoricalRatesRequestFormat)[keyof typeof CurrencyHistoricalRatesRequestFormat];
