// This file was auto-generated by Fern from our API Definition.

export const CurrencyConvertLatestRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type CurrencyConvertLatestRequestFormat =
    (typeof CurrencyConvertLatestRequestFormat)[keyof typeof CurrencyConvertLatestRequestFormat];
