// This file was auto-generated by Fern from our API Definition.

export const CurrencyHistoricalLimitsRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type CurrencyHistoricalLimitsRequestFormat =
    (typeof CurrencyHistoricalLimitsRequestFormat)[keyof typeof CurrencyHistoricalLimitsRequestFormat];
