// This file was auto-generated by Fern from our API Definition.

export const CurrencyConvertByIpRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type CurrencyConvertByIpRequestFormat =
    (typeof CurrencyConvertByIpRequestFormat)[keyof typeof CurrencyConvertByIpRequestFormat];
