// This file was auto-generated by Fern from our API Definition.

export const CurrencyLatestRatesRequestUpdates = {
    OneD: "1d",
    OneH: "1h",
    TenM: "10m",
    OneM: "1m",
} as const;
export type CurrencyLatestRatesRequestUpdates =
    (typeof CurrencyLatestRatesRequestUpdates)[keyof typeof CurrencyLatestRatesRequestUpdates];
