// This file was auto-generated by Fern from our API Definition.

export interface CurrencyConvertHistoricalResponse {
    /** For the latest rates converter, it is the date and time with timezone (UTC) when the rate was recorded. For historical converter, it is the date provided in the input (format: YYYY-MM-DD). */
    date: string;
    /** Base currency code (the currency being converted from). */
    from: string;
    /** Desired currency code (the currency to convert to). */
    to: string;
    /** Conversion rate from base currency to desired currency. */
    rate: string;
    /** The amount in base currency to be converted. */
    givenAmount: string;
    /** The result of the conversion in the desired currency. */
    convertedAmount: string;
}
