// This file was auto-generated by Fern from our API Definition.

export interface CurrencySymbolsResponse {
    /** A map of all currency symbols keyed by currency code; value is the full currency name. */
    currencySymbols: Record<string, string>;
}
