// This file was auto-generated by Fern from our API Definition.

export const CurrentWeatherRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type CurrentWeatherRequestFormat =
    (typeof CurrentWeatherRequestFormat)[keyof typeof CurrentWeatherRequestFormat];
