// This file was auto-generated by Fern from our API Definition.

export interface CurrencyHistoricalLimitsResponse {
    /** Availability date range per currency, formatted "YYYY-MM-DD to YYYY-MM-DD". */
    availabilityPeriod: Record<string, string>;
}
