// This file was auto-generated by Fern from our API Definition.

export interface CurrencyTimeSeriesResponse {
    /** Starting date of the interval (provided via input). */
    startDate: string;
    /** Ending date of the interval (provided via input). */
    endDate: string;
    /** Base currency with respect to which all rates are calculated. */
    base: string;
    /** List of historical exchange rates within the specified interval. */
    historicalRatesList: CurrencyTimeSeriesResponse.HistoricalRatesList.Item[];
}

export namespace CurrencyTimeSeriesResponse {
    export type HistoricalRatesList = HistoricalRatesList.Item[];

    export namespace HistoricalRatesList {
        export interface Item {
            /** Date of the specific exchange rates. */
            date: string;
            /** A map of currency symbols to their respective exchange rates for the given date. */
            rates: Record<string, string>;
        }
    }
}
