// This file was auto-generated by Fern from our API Definition.

export const CurrencyTimeSeriesRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type CurrencyTimeSeriesRequestFormat =
    (typeof CurrencyTimeSeriesRequestFormat)[keyof typeof CurrencyTimeSeriesRequestFormat];
