// This file was auto-generated by Fern from our API Definition.

export const CurrencyConvertByIpRequestUpdates = {
    OneD: "1d",
    OneH: "1h",
    TenM: "10m",
    OneM: "1m",
} as const;
export type CurrencyConvertByIpRequestUpdates =
    (typeof CurrencyConvertByIpRequestUpdates)[keyof typeof CurrencyConvertByIpRequestUpdates];
