// This file was auto-generated by Fern from our API Definition.

export const CurrencyFluctuationRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type CurrencyFluctuationRequestFormat =
    (typeof CurrencyFluctuationRequestFormat)[keyof typeof CurrencyFluctuationRequestFormat];
