// This file was auto-generated by Fern from our API Definition.

export interface DomainSslLookupResponse {
    domainName: string;
    queryTime: string;
    sslCertificates: DomainSslLookupResponse.SslCertificates.Item[];
    sslRaw?: string | undefined;
}

export namespace DomainSslLookupResponse {
    export type SslCertificates = SslCertificates.Item[];

    export namespace SslCertificates {
        export interface Item {
            chainOrder: string;
            authenticationType: string;
            validityStartDate: string;
            validityEndDate: string;
            serialNumber: string;
            signatureAlgorithm: string;
            subject: Item.Subject;
            issuer: Item.Issuer;
            publicKey: Item.PublicKey;
            extensions: Item.Extensions;
            /** Raw certificate in PEM format */
            pemRaw?: string | undefined;
        }

        export namespace Item {
            export interface Subject {
                commonName: string;
                organization?: string | undefined;
                organizationalUnit?: string | undefined;
                locality?: string | undefined;
                state?: string | undefined;
                country?: string | undefined;
                incCountry?: string | undefined;
                incState?: string | undefined;
                businessCategory?: string | undefined;
                street?: string | undefined;
                postalCode?: string | undefined;
                serialNumber?: string | undefined;
            }

            export interface Issuer {
                commonName: string;
                organization?: string | undefined;
                organizationalUnit?: string | undefined;
                locality?: string | undefined;
                state?: string | undefined;
                country?: string | undefined;
                incCountry?: string | undefined;
                incState?: string | undefined;
                businessCategory?: string | undefined;
                street?: string | undefined;
                postalCode?: string | undefined;
                serialNumber?: string | undefined;
            }

            export interface PublicKey {
                keySize: string;
                keyAlgorithm: string;
                pemRaw: string;
            }

            export interface Extensions {
                authorityKeyIdentifier: string;
                subjectKeyIdentifier: string;
                keyUsages: string[];
                extendedKeyUsages: string[];
                crlDistributionPoints?: string[] | undefined;
                authorityInfoAccess: Extensions.AuthorityInfoAccess;
                subjectAlternativeNames?: Extensions.SubjectAlternativeNames | undefined;
                certificatePolicies: Extensions.CertificatePolicies;
            }

            export namespace Extensions {
                export interface AuthorityInfoAccess {
                    issuers: string[];
                    ocsp: string[];
                }

                export interface SubjectAlternativeNames {
                    dnsNames?: string[] | undefined;
                    emailAddresses?: string[] | undefined;
                    ipAddresses?: string[] | undefined;
                    uris?: string[] | undefined;
                }

                export interface CertificatePolicies {
                    policyId: string;
                    policyQualifier?: CertificatePolicies.PolicyQualifier | undefined;
                }

                export namespace CertificatePolicies {
                    export interface PolicyQualifier {
                        oid?: string | undefined;
                        cpsUri?: string | undefined;
                        userNotice?: PolicyQualifier.UserNotice | undefined;
                    }

                    export namespace PolicyQualifier {
                        export interface UserNotice {
                            explicitText?: string | undefined;
                            noticeRef?: UserNotice.NoticeRef | undefined;
                        }

                        export namespace UserNotice {
                            export interface NoticeRef {
                                organization?: string | undefined;
                                noticeNumbers?: string | undefined;
                            }
                        }
                    }
                }
            }
        }
    }
}
