// This file was auto-generated by Fern from our API Definition.

export const DomainWhoisHistoryRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type DomainWhoisHistoryRequestFormat =
    (typeof DomainWhoisHistoryRequestFormat)[keyof typeof DomainWhoisHistoryRequestFormat];
