// This file was auto-generated by Fern from our API Definition.

/**
 * Current WHOIS registration record for the requested domain.
 */
export interface DomainWhoisLookupV2Response {
    /** true if the request was successfully processed. */
    status: boolean;
    /** Domain name that was queried. */
    domain_name: string;
    /** Timestamp when the WHOIS query was executed. */
    query_time: string;
    /** WHOIS or RDAP server that provided this record. */
    whois_server: string;
    /** Domain registration status; 'restricted' means the registry withholds registration details. */
    domain_registered: DomainWhoisLookupV2Response.DomainRegistered;
    /** Indicates if DNSSEC or secure DNS is enabled for the domain. */
    secure_dns?: boolean | undefined;
    /** Internal domain registry handle/ID. */
    domain_handle?: string | undefined;
    /** Date the domain was originally registered, when the domain is registered. */
    create_date?: string | undefined;
    /** Date the domain registration was last updated, when the domain is registered. */
    update_date?: string | undefined;
    /** Date the domain registration is set to expire, when the domain is registered. */
    expiry_date?: string | undefined;
    /** Registrar of record for a domain, as published by either the registrar or the registry. */
    domain_registrar?: DomainWhoisLookupV2Response.DomainRegistrar | undefined;
    /** A contact record (registrant, administrative, technical, billing, or reseller) published in the domain's WHOIS record. */
    reseller_contact?: DomainWhoisLookupV2Response.ResellerContact | undefined;
    /** A contact record (registrant, administrative, technical, billing, or reseller) published in the domain's WHOIS record. */
    registrant_contact?: DomainWhoisLookupV2Response.RegistrantContact | undefined;
    /** A contact record (registrant, administrative, technical, billing, or reseller) published in the domain's WHOIS record. */
    administrative_contact?: DomainWhoisLookupV2Response.AdministrativeContact | undefined;
    /** A contact record (registrant, administrative, technical, billing, or reseller) published in the domain's WHOIS record. */
    technical_contact?: DomainWhoisLookupV2Response.TechnicalContact | undefined;
    /** A contact record (registrant, administrative, technical, billing, or reseller) published in the domain's WHOIS record. */
    billing_contact?: DomainWhoisLookupV2Response.BillingContact | undefined;
    /** Registrar's abuse-reporting contact. */
    abuse_contact?: DomainWhoisLookupV2Response.AbuseContact | undefined;
    /** Domain eligibility information (populated for TLDs with registrant eligibility requirements, e.g. .eu). */
    eligibility_info?: DomainWhoisLookupV2Response.EligibilityInfo | undefined;
    /** Name servers currently recorded for the domain. */
    name_servers?: string[] | undefined;
    /** EPP domain status codes currently recorded for the domain. */
    domain_status?: string[] | undefined;
    /** Raw WHOIS text as returned by the registrar's WHOIS server. */
    whois_raw_domain?: string | undefined;
    /** Registry-level (as opposed to registrar-level) WHOIS data, sourced directly from the TLD registry. */
    registry_data?: DomainWhoisLookupV2Response.RegistryData | undefined;
}

export namespace DomainWhoisLookupV2Response {
    /** Domain registration status; 'restricted' means the registry withholds registration details. */
    export const DomainRegistered = {
        Yes: "yes",
        No: "no",
        Restricted: "restricted",
    } as const;
    export type DomainRegistered = (typeof DomainRegistered)[keyof typeof DomainRegistered];

    /**
     * Registrar of record for a domain, as published by either the registrar or the registry.
     */
    export interface DomainRegistrar {
        /** IANA registrar ID. */
        iana_id?: string | undefined;
        /** Registrar identifier. */
        id?: string | undefined;
        /** Type of registrar ID (e.g. IANA). */
        id_type?: string | undefined;
        /** Registrar handle. */
        handle?: string | undefined;
        /** Registry-specific registrar ID. */
        registry_id?: string | undefined;
        /** Registry authority name. */
        authoritative_registry_name?: string | undefined;
        /** Registrar organization number. */
        organization_number?: string | undefined;
        /** Indicates if the registrar is a sponsor. */
        is_sponsor?: boolean | undefined;
        /** Registrar's ICANN accreditation status (e.g. accredited), when published at the registrar level. */
        status?: string | undefined;
        /** Registered name of the registrar. */
        registrar_name?: string | undefined;
        /** Lowercased, normalized form of the registrar name, when published at the registrar level. */
        normalized_name?: string | undefined;
        /** WHOIS server operated by the registrar. */
        whois_server?: string | undefined;
        /** RDAP server URL operated by the registrar, when published at the registrar level. */
        rdap_server?: string | undefined;
        /** Registrar's website URL. */
        website_url?: string | undefined;
        /** Registrar abuse or contact email address. */
        email_address?: string | undefined;
        /** Registrar contact phone number. */
        phone_number?: string | undefined;
    }

    /**
     * A contact record (registrant, administrative, technical, billing, or reseller) published in the domain's WHOIS record.
     */
    export interface ResellerContact {
        /** Contact's full name. */
        name?: string | undefined;
        /** Contact's organization or company name. */
        company?: string | undefined;
        /** Street address. */
        street?: string | undefined;
        /** City. */
        city?: string | undefined;
        /** State or province. */
        state?: string | undefined;
        /** Postal/ZIP code. */
        zip_code?: string | undefined;
        /** Full country name. */
        country_name?: string | undefined;
        /** ISO 3166-1 alpha-2 country code. */
        country_code?: string | undefined;
        /** Contact email address, or a privacy-service redirect instruction. */
        email_address?: string | undefined;
        /** Contact phone number. */
        phone?: string | undefined;
        /** Contact fax number. */
        fax?: string | undefined;
        /** Full combined mailing address, when published as a single string. */
        mailing_address?: string | undefined;
    }

    /**
     * A contact record (registrant, administrative, technical, billing, or reseller) published in the domain's WHOIS record.
     */
    export interface RegistrantContact {
        /** Contact ID. */
        id?: string | undefined;
        /** Contact's full name. */
        name?: string | undefined;
        /** Contact's organization or company name. */
        company?: string | undefined;
        /** Street address. */
        street?: string | undefined;
        /** City. */
        city?: string | undefined;
        /** State or province. */
        state?: string | undefined;
        /** Postal/ZIP code. */
        zip_code?: string | undefined;
        /** Full country name. */
        country_name?: string | undefined;
        /** ISO 3166-1 alpha-2 country code. */
        country_code?: string | undefined;
        /** Contact email address, or a privacy-service redirect instruction. */
        email_address?: string | undefined;
        /** Contact phone number. */
        phone?: string | undefined;
        /** Contact fax number. */
        fax?: string | undefined;
        /** Full combined mailing address, when published as a single string. */
        mailing_address?: string | undefined;
    }

    /**
     * A contact record (registrant, administrative, technical, billing, or reseller) published in the domain's WHOIS record.
     */
    export interface AdministrativeContact {
        /** Contact ID. */
        id?: string | undefined;
        /** Contact's full name. */
        name?: string | undefined;
        /** Contact's organization or company name. */
        company?: string | undefined;
        /** Street address. */
        street?: string | undefined;
        /** City. */
        city?: string | undefined;
        /** State or province. */
        state?: string | undefined;
        /** Postal/ZIP code. */
        zip_code?: string | undefined;
        /** Full country name. */
        country_name?: string | undefined;
        /** ISO 3166-1 alpha-2 country code. */
        country_code?: string | undefined;
        /** Contact email address, or a privacy-service redirect instruction. */
        email_address?: string | undefined;
        /** Contact phone number. */
        phone?: string | undefined;
        /** Contact fax number. */
        fax?: string | undefined;
        /** Full combined mailing address, when published as a single string. */
        mailing_address?: string | undefined;
    }

    /**
     * A contact record (registrant, administrative, technical, billing, or reseller) published in the domain's WHOIS record.
     */
    export interface TechnicalContact {
        /** Contact ID. */
        id?: string | undefined;
        /** Contact's full name. */
        name?: string | undefined;
        /** Contact's organization or company name. */
        company?: string | undefined;
        /** Street address. */
        street?: string | undefined;
        /** City. */
        city?: string | undefined;
        /** State or province. */
        state?: string | undefined;
        /** Postal/ZIP code. */
        zip_code?: string | undefined;
        /** Full country name. */
        country_name?: string | undefined;
        /** ISO 3166-1 alpha-2 country code. */
        country_code?: string | undefined;
        /** Contact email address, or a privacy-service redirect instruction. */
        email_address?: string | undefined;
        /** Contact phone number. */
        phone?: string | undefined;
        /** Contact fax number. */
        fax?: string | undefined;
        /** Full combined mailing address, when published as a single string. */
        mailing_address?: string | undefined;
    }

    /**
     * A contact record (registrant, administrative, technical, billing, or reseller) published in the domain's WHOIS record.
     */
    export interface BillingContact {
        /** Contact's full name. */
        name?: string | undefined;
        /** Contact's organization or company name. */
        company?: string | undefined;
        /** Street address. */
        street?: string | undefined;
        /** City. */
        city?: string | undefined;
        /** State or province. */
        state?: string | undefined;
        /** Postal/ZIP code. */
        zip_code?: string | undefined;
        /** Full country name. */
        country_name?: string | undefined;
        /** ISO 3166-1 alpha-2 country code. */
        country_code?: string | undefined;
        /** Contact email address, or a privacy-service redirect instruction. */
        email_address?: string | undefined;
        /** Contact phone number. */
        phone?: string | undefined;
        /** Contact fax number. */
        fax?: string | undefined;
        /** Full combined mailing address, when published as a single string. */
        mailing_address?: string | undefined;
    }

    /**
     * Registrar's abuse-reporting contact.
     */
    export interface AbuseContact {
        /** Name of the abuse contact at the registrar. */
        registrar_name?: string | undefined;
        /** Abuse contact email. */
        email_address?: string | undefined;
        /** Abuse contact phone. */
        phone_number?: string | undefined;
    }

    /**
     * Domain eligibility information (populated for TLDs with registrant eligibility requirements, e.g. .eu).
     */
    export interface EligibilityInfo {
        /** Eligibility ID. */
        id?: string | undefined;
        /** Eligibility name. */
        name?: string | undefined;
        /** Eligibility type. */
        type?: string | undefined;
    }

    /**
     * Registry-level (as opposed to registrar-level) WHOIS data, sourced directly from the TLD registry.
     */
    export interface RegistryData {
        /** Domain name as recorded by the registry. */
        domain_name?: string | undefined;
        /** Timestamp when the registry-level record was queried. */
        query_time?: string | undefined;
        /** Registry WHOIS server that returned this data. */
        whois_server?: string | undefined;
        /** Domain registration status as recorded by the registry. */
        domain_registered?: RegistryData.DomainRegistered | undefined;
        /** Domain creation date as recorded by the registry. */
        create_date?: string | undefined;
        /** Domain last-updated date as recorded by the registry. */
        update_date?: string | undefined;
        /** Domain expiry date as recorded by the registry. */
        expiry_date?: string | undefined;
        /** Name servers as recorded by the registry. */
        name_servers?: string[] | undefined;
        /** EPP domain status codes as recorded by the registry. */
        domain_status?: string[] | undefined;
        /** Raw WHOIS text as returned directly by the registry server. */
        whois_raw_registery?: string | undefined;
        /** Registrar of record for a domain, as published by either the registrar or the registry. */
        domain_registrar?: RegistryData.DomainRegistrar | undefined;
    }

    export namespace RegistryData {
        /** Domain registration status as recorded by the registry. */
        export const DomainRegistered = {
            Yes: "yes",
            No: "no",
            Restricted: "restricted",
        } as const;
        export type DomainRegistered = (typeof DomainRegistered)[keyof typeof DomainRegistered];

        /**
         * Registrar of record for a domain, as published by either the registrar or the registry.
         */
        export interface DomainRegistrar {
            /** IANA registrar ID. */
            iana_id?: string | undefined;
            /** Registrar identifier. */
            id?: string | undefined;
            /** Type of registrar ID (e.g. IANA). */
            id_type?: string | undefined;
            /** Registrar handle. */
            handle?: string | undefined;
            /** Registry-specific registrar ID. */
            registry_id?: string | undefined;
            /** Registry authority name. */
            authoritative_registry_name?: string | undefined;
            /** Registrar organization number. */
            organization_number?: string | undefined;
            /** Indicates if the registrar is a sponsor. */
            is_sponsor?: boolean | undefined;
            /** Registrar's ICANN accreditation status (e.g. accredited), when published at the registrar level. */
            status?: string | undefined;
            /** Registered name of the registrar. */
            registrar_name?: string | undefined;
            /** Lowercased, normalized form of the registrar name, when published at the registrar level. */
            normalized_name?: string | undefined;
            /** WHOIS server operated by the registrar. */
            whois_server?: string | undefined;
            /** RDAP server URL operated by the registrar, when published at the registrar level. */
            rdap_server?: string | undefined;
            /** Registrar's website URL. */
            website_url?: string | undefined;
            /** Registrar abuse or contact email address. */
            email_address?: string | undefined;
            /** Registrar contact phone number. */
            phone_number?: string | undefined;
        }
    }
}
