// This file was auto-generated by Fern from our API Definition.

export const DomainDnsReverseRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type DomainDnsReverseRequestFormat =
    (typeof DomainDnsReverseRequestFormat)[keyof typeof DomainDnsReverseRequestFormat];
