// This file was auto-generated by Fern from our API Definition.

export const DomainDnsLookupRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type DomainDnsLookupRequestFormat =
    (typeof DomainDnsLookupRequestFormat)[keyof typeof DomainDnsLookupRequestFormat];
