// This file was auto-generated by Fern from our API Definition.

export const DomainSslChainLookupRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type DomainSslChainLookupRequestFormat =
    (typeof DomainSslChainLookupRequestFormat)[keyof typeof DomainSslChainLookupRequestFormat];
