// This file was auto-generated by Fern from our API Definition.

export interface DomainWhoisHistoryResponse {
    /** Determines whether the request was successfully processed or not. */
    status: boolean;
    /** Indicates that this response contains historical data. */
    whois: DomainWhoisHistoryResponse.Whois;
    /** Shows the total number of records found for the queried domain. */
    total_records: string;
    whois_domains_historical: DomainWhoisHistoryResponse.WhoisDomainsHistorical.Item[];
}

export namespace DomainWhoisHistoryResponse {
    /** Indicates that this response contains historical data. */
    export const Whois = {
        Historical: "historical",
    } as const;
    export type Whois = (typeof Whois)[keyof typeof Whois];
    export type WhoisDomainsHistorical = WhoisDomainsHistorical.Item[];

    export namespace WhoisDomainsHistorical {
        export interface Item {
            /** Shows the number of the record in the array. */
            num: number;
            /** Always true. */
            status: boolean;
            /** Domain name which was queried. */
            domain_name: string;
            /** The timestamp when the query was made. */
            query_time: string;
            /** The WHOIS server that provided the domain information. */
            whois_server: string;
            /** Domain registration status. */
            domain_registered: Item.DomainRegistered;
            /** Date when the domain was initially registered. */
            create_date?: string | undefined;
            /** The date of the most recent update to the domain registration. */
            update_date?: string | undefined;
            /** The date when the domain registration will expire if not renewed. */
            expiry_date?: string | undefined;
            domain_registrar?: Item.DomainRegistrar | undefined;
            reseller_contact?: Item.ResellerContact | undefined;
            registrant_contact?: Item.RegistrantContact | undefined;
            administrative_contact?: Item.AdministrativeContact | undefined;
            technical_contact?: Item.TechnicalContact | undefined;
            billing_contact?: Item.BillingContact | undefined;
            name_servers?: string[] | undefined;
            domain_status?: string[] | undefined;
            whois_raw_domain?: string | undefined;
            registry_data?: Item.RegistryData | undefined;
        }

        export namespace Item {
            /** Domain registration status. */
            export const DomainRegistered = {
                Yes: "yes",
                No: "no",
                Restricted: "restricted",
            } as const;
            export type DomainRegistered = (typeof DomainRegistered)[keyof typeof DomainRegistered];

            export interface DomainRegistrar {
                iana_id?: string | undefined;
                registrar_name?: string | undefined;
                whois_server?: string | undefined;
                website_url?: string | undefined;
                email_address?: string | undefined;
                phone_number?: string | undefined;
            }

            export interface ResellerContact {
                name?: string | undefined;
                company?: string | undefined;
                street?: string | undefined;
                city?: string | undefined;
                state?: string | undefined;
                zip_code?: string | undefined;
                country_name?: string | undefined;
                country_code?: string | undefined;
                email_address?: string | undefined;
                phone?: string | undefined;
                fax?: string | undefined;
                mailing_address?: string | undefined;
            }

            export interface RegistrantContact {
                name?: string | undefined;
                company?: string | undefined;
                street?: string | undefined;
                city?: string | undefined;
                state?: string | undefined;
                zip_code?: string | undefined;
                country_name?: string | undefined;
                country_code?: string | undefined;
                emailaddress?: string | undefined;
                phone?: string | undefined;
                fax?: string | undefined;
                mailingaddress?: string | undefined;
            }

            export interface AdministrativeContact {
                name?: string | undefined;
                company?: string | undefined;
                street?: string | undefined;
                city?: string | undefined;
                state?: string | undefined;
                zip_code?: string | undefined;
                country_name?: string | undefined;
                country_code?: string | undefined;
                emailaddress?: string | undefined;
                phone?: string | undefined;
                fax?: string | undefined;
                mailingaddress?: string | undefined;
            }

            export interface TechnicalContact {
                name?: string | undefined;
                company?: string | undefined;
                street?: string | undefined;
                city?: string | undefined;
                state?: string | undefined;
                zip_code?: string | undefined;
                country_name?: string | undefined;
                country_code?: string | undefined;
                emailaddress?: string | undefined;
                phone?: string | undefined;
                fax?: string | undefined;
                mailingaddress?: string | undefined;
            }

            export interface BillingContact {
                name?: string | undefined;
                company?: string | undefined;
                street?: string | undefined;
                city?: string | undefined;
                state?: string | undefined;
                zip_code?: string | undefined;
                country_name?: string | undefined;
                country_code?: string | undefined;
                emailaddress?: string | undefined;
                phone?: string | undefined;
                fax?: string | undefined;
                mailingaddress?: string | undefined;
            }

            export interface RegistryData {
                domain_name?: string | undefined;
                query_time?: string | undefined;
                whois_server?: string | undefined;
                domain_registered?: RegistryData.DomainRegistered | undefined;
                create_date?: string | undefined;
                update_date?: string | undefined;
                expiry_date?: string | undefined;
                name_servers?: string[] | undefined;
                domain_status?: string[] | undefined;
                whois_raw_registry?: string | undefined;
                domain_registrar?: RegistryData.DomainRegistrar | undefined;
            }

            export namespace RegistryData {
                export const DomainRegistered = {
                    Yes: "yes",
                    No: "no",
                    Restricted: "restricted",
                } as const;
                export type DomainRegistered = (typeof DomainRegistered)[keyof typeof DomainRegistered];

                export interface DomainRegistrar {
                    iana_id?: string | undefined;
                    registrar_name?: string | undefined;
                    whois_server?: string | undefined;
                    website_url?: string | undefined;
                    email_address?: string | undefined;
                    phone_number?: string | undefined;
                }
            }
        }
    }
}
