// This file was auto-generated by Fern from our API Definition.

export const DomainAvailabilitySuggestionsRequestSource = {
    Dns: "dns",
    Whois: "whois",
} as const;
export type DomainAvailabilitySuggestionsRequestSource =
    (typeof DomainAvailabilitySuggestionsRequestSource)[keyof typeof DomainAvailabilitySuggestionsRequestSource];
