// This file was auto-generated by Fern from our API Definition.

export const DomainWhoisReverseRequestMode = {
    Default: "default",
    Mini: "mini",
} as const;
export type DomainWhoisReverseRequestMode =
    (typeof DomainWhoisReverseRequestMode)[keyof typeof DomainWhoisReverseRequestMode];
