// This file was auto-generated by Fern from our API Definition.

export interface DomainDnsLookupResponse {
    /** Indicates whether the query was processed successfully. */
    status: boolean;
    /** Time at which the query was made (Format:YYYY-MM-DD HH:mm:ss). */
    queryTime: string;
    /** Queried domain. */
    domainName: string;
    /** Indicates whether the domain is registered. */
    domainRegistered: boolean;
    dnsTypes: DomainDnsLookupResponse.DnsTypes;
    /** List of DNS records, each based on its type. */
    dnsRecords: DomainDnsLookupResponse.DnsRecords.Item[];
}

export namespace DomainDnsLookupResponse {
    export interface DnsTypes {
        A?: number | undefined;
        AAAA?: number | undefined;
        CNAME?: number | undefined;
        MX?: number | undefined;
        NS?: number | undefined;
        SOA?: number | undefined;
        TXT?: number | undefined;
        SPF?: number | undefined;
    }

    export type DnsRecords = DnsRecords.Item[];

    export namespace DnsRecords {
        export type Item =
            | {
                  name: string;
                  type: number;
                  dnsType: "A" | "AAAA";
                  ttl: number;
                  rawText: string;
                  rRsetType: number;
                  address: string;
              }
            | {
                  name: string;
                  type: number;
                  dnsType: "CNAME";
                  ttl: number;
                  rawText: string;
                  rRsetType: number;
                  target: string;
              }
            | {
                  name: string;
                  type: number;
                  dnsType: "MX";
                  ttl: number;
                  rawText: string;
                  rRsetType: number;
                  target: string;
                  priority: number;
              }
            | {
                  name: string;
                  type: number;
                  dnsType: "NS";
                  ttl: number;
                  rawText: string;
                  rRsetType: number;
                  singleName: string;
              }
            | {
                  name: string;
                  type: number;
                  dnsType: "SOA";
                  ttl: number;
                  rawText: string;
                  rRsetType: number;
                  admin: string;
                  host: string;
                  expire: number;
                  minimum: number;
                  refresh: number;
                  retry: number;
                  serial: number;
              }
            | {
                  name: string;
                  type: number;
                  dnsType: "TXT" | "SPF";
                  ttl: number;
                  rawText: string;
                  rRsetType: number;
                  strings: string[];
              };
    }
}
