// This file was auto-generated by Fern from our API Definition.

export const DomainAvailabilityCheckRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type DomainAvailabilityCheckRequestFormat =
    (typeof DomainAvailabilityCheckRequestFormat)[keyof typeof DomainAvailabilityCheckRequestFormat];
