// This file was auto-generated by Fern from our API Definition.

export interface DomainWhoisReverseResponse {
    totalResult?: number | undefined;
    totalPages?: number | undefined;
    currentPage?: number | undefined;
    whois_domains_historical?: DomainWhoisReverseResponse.WhoisDomainsHistorical.Item[] | undefined;
}

export namespace DomainWhoisReverseResponse {
    export type WhoisDomainsHistorical = WhoisDomainsHistorical.Item[];

    export namespace WhoisDomainsHistorical {
        export type Item =
            | {
                  num: number;
                  status: boolean;
                  domain_name: string;
                  query_time: string;
                  whois_server: string;
                  domain_registered: "yes" | "no" | "restricted";
                  create_date?: string | undefined;
                  update_date?: string | undefined;
                  expiry_date?: string | undefined;
                  domain_registrar?:
                      | {
                            iana_id?: string | undefined;
                            registrar_name?: string | undefined;
                            whois_server?: string | undefined;
                            website_url?: string | undefined;
                            email_address?: string | undefined;
                            phone_number?: string | undefined;
                        }
                      | undefined;
                  reseller_contact?:
                      | {
                            name?: string | undefined;
                            company?: string | undefined;
                            street?: string | undefined;
                            city?: string | undefined;
                            state?: string | undefined;
                            zip_code?: string | undefined;
                            country_name?: string | undefined;
                            country_code?: string | undefined;
                            email_address?: string | undefined;
                            phone?: string | undefined;
                            fax?: string | undefined;
                            mailing_address?: string | undefined;
                        }
                      | undefined;
                  registrant_contact?:
                      | {
                            name?: string | undefined;
                            company?: string | undefined;
                            street?: string | undefined;
                            city?: string | undefined;
                            state?: string | undefined;
                            zip_code?: string | undefined;
                            country_name?: string | undefined;
                            country_code?: string | undefined;
                            email_address?: string | undefined;
                            phone?: string | undefined;
                            fax?: string | undefined;
                            mailing_address?: string | undefined;
                        }
                      | undefined;
                  administrative_contact?:
                      | {
                            name?: string | undefined;
                            company?: string | undefined;
                            street?: string | undefined;
                            city?: string | undefined;
                            state?: string | undefined;
                            zip_code?: string | undefined;
                            country_name?: string | undefined;
                            country_code?: string | undefined;
                            email_address?: string | undefined;
                            phone?: string | undefined;
                            fax?: string | undefined;
                            mailing_address?: string | undefined;
                        }
                      | undefined;
                  technical_contact?:
                      | {
                            name?: string | undefined;
                            company?: string | undefined;
                            street?: string | undefined;
                            city?: string | undefined;
                            state?: string | undefined;
                            zip_code?: string | undefined;
                            country_name?: string | undefined;
                            country_code?: string | undefined;
                            email_address?: string | undefined;
                            phone?: string | undefined;
                            fax?: string | undefined;
                            mailing_address?: string | undefined;
                        }
                      | undefined;
                  billing_contact?:
                      | {
                            name?: string | undefined;
                            company?: string | undefined;
                            street?: string | undefined;
                            city?: string | undefined;
                            state?: string | undefined;
                            zip_code?: string | undefined;
                            country_name?: string | undefined;
                            country_code?: string | undefined;
                            email_address?: string | undefined;
                            phone?: string | undefined;
                            fax?: string | undefined;
                            mailing_address?: string | undefined;
                        }
                      | undefined;
                  name_servers?: string[] | undefined;
                  domain_status?: string[] | undefined;
                  whois_raw_domain?: string | undefined;
                  registry_data?:
                      | {
                            domain_name?: string | undefined;
                            query_time?: string | undefined;
                            whois_server?: string | undefined;
                            domain_registered?: ("yes" | "no" | "restricted") | undefined;
                            create_date?: string | undefined;
                            update_date?: string | undefined;
                            expiry_date?: string | undefined;
                            name_servers?: string[] | undefined;
                            domain_status?: string[] | undefined;
                            whois_raw_registry?: string | undefined;
                            domain_registrar?:
                                | {
                                      iana_id?: string | undefined;
                                      registrar_name?: string | undefined;
                                      whois_server?: string | undefined;
                                      website_url?: string | undefined;
                                      email_address?: string | undefined;
                                      phone_number?: string | undefined;
                                  }
                                | undefined;
                        }
                      | undefined;
              }
            | {
                  num: number;
                  domain_name: string;
                  create_date?: string | undefined;
                  update_date?: string | undefined;
                  expiry_date?: string | undefined;
                  name?: string | undefined;
                  email?: string | undefined;
                  companyname?: string | undefined;
              };
    }
}
