// This file was auto-generated by Fern from our API Definition.

export const DomainAvailabilityCheckRequestSource = {
    Dns: "dns",
    Whois: "whois",
} as const;
export type DomainAvailabilityCheckRequestSource =
    (typeof DomainAvailabilityCheckRequestSource)[keyof typeof DomainAvailabilityCheckRequestSource];
