// This file was auto-generated by Fern from our API Definition.

export const DomainTyposquattingRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type DomainTyposquattingRequestFormat =
    (typeof DomainTyposquattingRequestFormat)[keyof typeof DomainTyposquattingRequestFormat];
