// This file was auto-generated by Fern from our API Definition.

export interface DomainDnsHistoryResponse {
    totalRecords: number;
    totalPages: number;
    currentPage: number;
    historicalDnsRecords: DomainDnsHistoryResponse.HistoricalDnsRecords.Item[];
}

export namespace DomainDnsHistoryResponse {
    export type HistoricalDnsRecords = HistoricalDnsRecords.Item[];

    export namespace HistoricalDnsRecords {
        export interface Item {
            queryTime: string;
            domainName: string;
            dnsTypes: Item.DnsTypes;
            dnsRecords: Item.DnsRecords.Item[];
        }

        export namespace Item {
            export interface DnsTypes {
                A?: number | undefined;
                AAAA?: number | undefined;
                CNAME?: number | undefined;
                MX?: number | undefined;
                NS?: number | undefined;
                SOA?: number | undefined;
                TXT?: number | undefined;
                SPF?: number | undefined;
            }

            export type DnsRecords = DnsRecords.Item[];

            export namespace DnsRecords {
                export type Item =
                    | {
                          name: string;
                          type: number;
                          dnsType: "A" | "AAAA";
                          ttl: number;
                          rawText: string;
                          rRsetType: number;
                          address: string;
                      }
                    | {
                          name: string;
                          type: number;
                          dnsType: "CNAME";
                          ttl: number;
                          rawText: string;
                          rRsetType: number;
                          target: string;
                      }
                    | {
                          name: string;
                          type: number;
                          dnsType: "MX";
                          ttl: number;
                          rawText: string;
                          rRsetType: number;
                          target: string;
                          priority: number;
                      }
                    | {
                          name: string;
                          type: number;
                          dnsType: "NS";
                          ttl: number;
                          rawText: string;
                          rRsetType: number;
                          singleName: string;
                      }
                    | {
                          name: string;
                          type: number;
                          dnsType: "SOA";
                          ttl: number;
                          rawText: string;
                          rRsetType: number;
                          admin: string;
                          host: string;
                          expire: number;
                          minimum: number;
                          refresh: number;
                          retry: number;
                          serial: number;
                      }
                    | {
                          name: string;
                          type: number;
                          dnsType: "TXT" | "SPF";
                          ttl: number;
                          rawText: string;
                          rRsetType: number;
                          strings: string[];
                      };
            }
        }
    }
}
