// This file was auto-generated by Fern from our API Definition.

export const DomainDnsHistoryRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type DomainDnsHistoryRequestFormat =
    (typeof DomainDnsHistoryRequestFormat)[keyof typeof DomainDnsHistoryRequestFormat];
