// This file was auto-generated by Fern from our API Definition.

export const DomainWhoisLookupRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type DomainWhoisLookupRequestFormat =
    (typeof DomainWhoisLookupRequestFormat)[keyof typeof DomainWhoisLookupRequestFormat];
