// This file was auto-generated by Fern from our API Definition.

export type DomainAvailabilitySuggestionsResponse =
    /**
     * Returned when `sug=false` — availability for the queried domain only, no suggestions. */
    | {
          domain?: string | undefined;
          domainAvailability?: boolean | undefined;
      }
    /**
     * Returned when `sug` is omitted or `true` — the queried domain plus suggested alternatives. */
    | {
          domain_available_response?:
              | {
                    domain?: string | undefined;
                    domainAvailability?: boolean | undefined;
                    message?: string | undefined;
                }[]
              | undefined;
      };
