// This file was auto-generated by Fern from our API Definition.

export const DomainWhoisReverseRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type DomainWhoisReverseRequestFormat =
    (typeof DomainWhoisReverseRequestFormat)[keyof typeof DomainWhoisReverseRequestFormat];
