// This file was auto-generated by Fern from our API Definition.

export const DomainReputationRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type DomainReputationRequestFormat =
    (typeof DomainReputationRequestFormat)[keyof typeof DomainReputationRequestFormat];
