// This file was auto-generated by Fern from our API Definition.

export interface DomainAvailabilitySuggestionsResponse {
    domain_available_response: DomainAvailabilitySuggestionsResponse.DomainAvailableResponse.Item[];
}

export namespace DomainAvailabilitySuggestionsResponse {
    export type DomainAvailableResponse = DomainAvailableResponse.Item[];

    export namespace DomainAvailableResponse {
        export interface Item {
            domain: string;
            domainAvailability: boolean;
        }
    }
}
