// This file was auto-generated by Fern from our API Definition.

export const DomainWhoisLookupV2RequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type DomainWhoisLookupV2RequestFormat =
    (typeof DomainWhoisLookupV2RequestFormat)[keyof typeof DomainWhoisLookupV2RequestFormat];
