// This file was auto-generated by Fern from our API Definition.

export const DomainSslLookupRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type DomainSslLookupRequestFormat =
    (typeof DomainSslLookupRequestFormat)[keyof typeof DomainSslLookupRequestFormat];
