// This file was auto-generated by Fern from our API Definition.

export interface DomainAvailabilitySuggestionsResponse {
    domain_available_response?: DomainAvailabilitySuggestionsResponse.DomainAvailableResponse.Item[] | undefined;
}

export namespace DomainAvailabilitySuggestionsResponse {
    export type DomainAvailableResponse = DomainAvailableResponse.Item[];

    export namespace DomainAvailableResponse {
        export interface Item {
            domain?: string | undefined;
            domainAvailability?: boolean | undefined;
            /** Extra details if the domain is not registered. */
            message?: string | undefined;
        }
    }
}
