// This file was auto-generated by Fern from our API Definition.

export interface DomainSslLookupResponse {
    domainName: string;
    /** Timestamp when the query was executed (format YYYY-MM-DD HH:mm:ss, not ISO 8601). */
    queryTime: string;
    sslCertificates: DomainSslLookupResponse.SslCertificates.Item[];
    sslRaw?: string | undefined;
}

export namespace DomainSslLookupResponse {
    export type SslCertificates = SslCertificates.Item[];

    export namespace SslCertificates {
        export interface Item {
            chainOrder: string;
            authenticationType: string;
            validityStartDate: string;
            validityEndDate: string;
            serialNumber: string;
            signatureAlgorithm: string;
            subject: Item.Subject;
            issuer: Item.Issuer;
            publicKey: Item.PublicKey;
            extensions: Item.Extensions;
            /** Raw certificate in PEM format */
            pemRaw?: string | undefined;
        }

        export namespace Item {
            export interface Subject {
                commonName: string;
                organization?: string | undefined;
                organizationalUnit?: string | undefined;
                locality?: string | undefined;
                state?: string | undefined;
                country?: string | undefined;
                incCountry?: string | undefined;
                incState?: string | undefined;
                businessCategory?: string | undefined;
                street?: string | undefined;
                postalCode?: string | undefined;
                serialNumber?: string | undefined;
            }

            export interface Issuer {
                commonName: string;
                organization?: string | undefined;
                organizationalUnit?: string | undefined;
                locality?: string | undefined;
                state?: string | undefined;
                country?: string | undefined;
                incCountry?: string | undefined;
                incState?: string | undefined;
                businessCategory?: string | undefined;
                street?: string | undefined;
                postalCode?: string | undefined;
                serialNumber?: string | undefined;
            }

            export interface PublicKey {
                keySize: string;
                keyAlgorithm: string;
                pemRaw: string;
            }

            export interface Extensions {
                authorityKeyIdentifier: string;
                subjectKeyIdentifier: string;
                keyUsages: string[];
                extendedKeyUsages?: string[] | undefined;
                crlDistributionPoints?: string[] | undefined;
                authorityInfoAccess?: Extensions.AuthorityInfoAccess | undefined;
                subjectAlternativeNames?: Extensions.SubjectAlternativeNames | undefined;
                certificatePolicies?: Extensions.CertificatePolicies.Item[] | undefined;
            }

            export namespace Extensions {
                export interface AuthorityInfoAccess {
                    issuers?: string[] | undefined;
                    ocsp?: string[] | undefined;
                }

                export interface SubjectAlternativeNames {
                    dnsNames?: string[] | undefined;
                    emailAddresses?: string[] | undefined;
                    ipAddresses?: string[] | undefined;
                    uris?: string[] | undefined;
                }

                export type CertificatePolicies = CertificatePolicies.Item[];

                export namespace CertificatePolicies {
                    export interface Item {
                        /** Policy identifier */
                        policyId: string;
                        /** Policy qualifier details */
                        policyQualifier?: Item.PolicyQualifier | undefined;
                    }

                    export namespace Item {
                        /**
                         * Policy qualifier details
                         */
                        export interface PolicyQualifier {
                            /** Object identifier */
                            oid?: string | undefined;
                            /** URI of the CPS */
                            cpsUri?: string | undefined;
                            userNotice?: PolicyQualifier.UserNotice | undefined;
                        }

                        export namespace PolicyQualifier {
                            export interface UserNotice {
                                /** Explicit text notice */
                                explicitText?: string | undefined;
                                noticeRef?: UserNotice.NoticeRef | undefined;
                            }

                            export namespace UserNotice {
                                export interface NoticeRef {
                                    /** Organization providing the notice */
                                    organization?: string | undefined;
                                    /** Notice numbers */
                                    noticeNumbers?: string | undefined;
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
