// This file was auto-generated by Fern from our API Definition.

export const DomainDnsReverseRequestType = {
    A: "A",
    Aaaa: "AAAA",
    Mx: "MX",
    Ns: "NS",
    Soa: "SOA",
    Spf: "SPF",
    Txt: "TXT",
    Cname: "CNAME",
} as const;
export type DomainDnsReverseRequestType =
    (typeof DomainDnsReverseRequestType)[keyof typeof DomainDnsReverseRequestType];
