// This file was auto-generated by Fern from our API Definition.

export const EmailValidateRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type EmailValidateRequestFormat = (typeof EmailValidateRequestFormat)[keyof typeof EmailValidateRequestFormat];
