// This file was auto-generated by Fern from our API Definition.

export const FloodForecastRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type FloodForecastRequestFormat = (typeof FloodForecastRequestFormat)[keyof typeof FloodForecastRequestFormat];
