// This file was auto-generated by Fern from our API Definition.

export const FloodForecastRequestPrecision = {
    Daily: "daily",
} as const;
export type FloodForecastRequestPrecision =
    (typeof FloodForecastRequestPrecision)[keyof typeof FloodForecastRequestPrecision];
