// This file was auto-generated by Fern from our API Definition.

export const GeocoderSearchRequestFormat = {
    Json: "json",
} as const;
export type GeocoderSearchRequestFormat =
    (typeof GeocoderSearchRequestFormat)[keyof typeof GeocoderSearchRequestFormat];
