// This file was auto-generated by Fern from our API Definition.

export interface GeocoderSearchResponseItem {
    /** WGS84 latitude value for the location. */
    lat: number;
    /** WGS84 longitude value for the location. */
    lon: number;
    /** Name for the primary place searched. */
    name?: string | undefined;
    /** High-level category of the place, e.g., amenity, place, natural, building, highway. */
    category?: string | undefined;
    /** Specific kind within the category, e.g., fast_food, city, park, residential, house_number. */
    type?: string | undefined;
    /** Array describing the main POI and closely related elements at this location. */
    poi?: GeocoderSearchResponseItem.Poi.Item[] | undefined;
    /** Street or road name. */
    street?: string | undefined;
    /** Intra-city area below city level, e.g., suburb, borough, ward, district, tehsil, neighbourhood. */
    area?: string | undefined;
    /** Postal code of the area. */
    postcode?: string | undefined;
    /** Settlement label appropriate to the country, e.g., city, town, municipality. */
    city?: string | undefined;
    /** Second-tier administrative area, e.g., county, district, prefecture. */
    county?: string | undefined;
    /** Subdivision code, typically ISO-3166-2 (e.g., US-TX, PK-PB). */
    state_code?: string | undefined;
    /** First-tier administrative area, e.g., state, region, province, division. */
    state?: string | undefined;
    /** Two-letter country code in upper case, ISO-3166-1 alpha-2. */
    country_code: string;
    /** Country name of the searched place. */
    country: string;
    /** Single-line, human-readable address of the location. */
    full_address: string;
    /** Extent of the feature as [lat_min, lat_max, lon_min, lon_max] in WGS84 decimal degrees. */
    bounding_box: string[];
}

export namespace GeocoderSearchResponseItem {
    export type Poi = Poi.Item[];

    export namespace Poi {
        export interface Item {
            /** Name of the poi (point of interest) of the searched place. */
            name?: string | undefined;
            /** Category of the poi, e.g., amenity, place, natural, building, highway. */
            category?: string | undefined;
            /** Specific type of the category for the poi, e.g., fast_food, city, park, residential, house_number. */
            type?: string | undefined;
        }
    }
}
