// This file was auto-generated by Fern from our API Definition.

export const GeolocationLookupV2RequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type GeolocationLookupV2RequestFormat =
    (typeof GeolocationLookupV2RequestFormat)[keyof typeof GeolocationLookupV2RequestFormat];
