// This file was auto-generated by Fern from our API Definition.

export const GeolocationLookupRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type GeolocationLookupRequestFormat =
    (typeof GeolocationLookupRequestFormat)[keyof typeof GeolocationLookupRequestFormat];
