// This file was auto-generated by Fern from our API Definition.

export interface GeolocationLookupV2Response {
    /** The IP address used for the lookup (IPv4 or IPv6). */
    ip: string;
    /** The input domain, returned only for domain-based lookups. */
    domain?: string | undefined;
    /** Reverse DNS hostname (PTR) for the input IP; returns the input IP if not resolvable. */
    hostname?: string | undefined;
    /** Geographic location information for the IP. */
    location?: GeolocationLookupV2Response.Location | undefined;
    /** Country-specific metadata. */
    country_metadata?: GeolocationLookupV2Response.CountryMetadata | undefined;
    /** Network information for the IP. */
    network?: GeolocationLookupV2Response.Network | undefined;
    /** Autonomous System details for the IP. */
    asn?: GeolocationLookupV2Response.Asn | undefined;
    /** Company or ISP information mapped to the IP address. */
    company?: GeolocationLookupV2Response.Company | undefined;
    /** Currency information for the IP's country. */
    currency?: GeolocationLookupV2Response.Currency | undefined;
    /** Threat intelligence and security information for the IP. */
    security?: GeolocationLookupV2Response.Security | undefined;
    /** Abuse contact information for the IP. */
    abuse?: GeolocationLookupV2Response.Abuse | undefined;
    /** Time zone information for the IP's location. */
    time_zone?: GeolocationLookupV2Response.TimeZone | undefined;
    /** Parsed User-Agent details from the request. */
    user_agent?: GeolocationLookupV2Response.UserAgent | undefined;
}

export namespace GeolocationLookupV2Response {
    /**
     * Geographic location information for the IP.
     */
    export interface Location {
        /** 2-letter code of the continent. */
        continent_code: string;
        /** Name of the continent. */
        continent_name: string;
        /** Country code (ISO 3166-1 alpha-2) of the country. */
        country_code2: string;
        /** Country code (ISO 3166-1 alpha-3) of the country. */
        country_code3: string;
        /** Name of the country. */
        country_name: string;
        /** Official name (ISO 3166) of the country. */
        country_name_official: string;
        /** Name of the country's capital. */
        country_capital: string;
        /** Name of the state/province/region. */
        state_prov?: string | undefined;
        /** Code of the state/province/region. */
        state_code?: string | undefined;
        /** Name of the district or county. */
        district?: string | undefined;
        /** Name of the city. */
        city?: string | undefined;
        /** A more specific area in city or it can be same as city. */
        locality?: string | undefined;
        /** Circular radius in Km, where the IP address location can be found. */
        accuracy_radius?: string | undefined;
        /** Confidence level of the location match (e.g., low, medium, high). */
        confidence?: string | undefined;
        /** Designated Market Area (DMA) code used in the United States for media marketing. */
        dma_code?: (string | null) | undefined;
        /** ZIP/Postal code of the place. */
        zipcode?: string | undefined;
        /** Latitude of the place. */
        latitude: string;
        /** Longitude of the place. */
        longitude: string;
        /** Is the country belong to European Union? */
        is_eu: boolean;
        /** URL to get the country flag. */
        country_flag: string;
        /** Geoname ID of the place from geonames.org. */
        geoname_id?: string | undefined;
        /** Emoji of the Country flag. */
        country_emoji?: string | undefined;
    }

    /**
     * Country-specific metadata.
     */
    export interface CountryMetadata {
        /** Calling code/Dialing code of the country. */
        calling_code: string;
        /** Top Level Domain Name (TLD) of the country, which is also called ccTLD. */
        tld: string;
        /** List of the languages' codes, spoken in the country. */
        languages: string[];
    }

    /**
     * Network information for the IP.
     */
    export interface Network {
        /** Network access type classification (e.g., DSL, Cable, Mobile, 5G) when available. */
        connection_type?: string | undefined;
        /** Network prefix in CIDR notation that contains the IP. */
        route?: string | undefined;
        /** true if the IP is anycast (same IP announced from multiple locations). */
        is_anycast?: boolean | undefined;
    }

    /**
     * Autonomous System details for the IP.
     */
    export interface Asn {
        /** ASN identifier in AS<number> format associated with the IP's network. */
        as_number?: string | undefined;
        /** ASN operator name. */
        organization?: string | undefined;
        /** ASN registration country as ISO 3166-1 alpha-2. */
        country?: string | undefined;
        /** ASN category (ISP, HOSTING, BUSINESS, etc.). */
        type?: string | undefined;
        /** ASN operator domain name. */
        domain?: string | undefined;
        /** ASN allocation date in YYYY-MM-DD format. */
        date_allocated?: string | undefined;
        /** Regional Internet Registry that allocated the ASN. */
        rir?: string | undefined;
    }

    /**
     * Company or ISP information mapped to the IP address.
     */
    export interface Company {
        /** Company name mapped to the IP. */
        name?: string | undefined;
        /** Company category (ISP, HOSTING, BUSINESS, etc.). */
        type?: string | undefined;
        /** Company domain name. */
        domain?: string | undefined;
    }

    /**
     * Currency information for the IP's country.
     */
    export interface Currency {
        /** Currency code (ISO 4217). */
        code?: string | undefined;
        /** Currency name (ISO 4217). */
        name?: string | undefined;
        /** Currency symbol. */
        symbol?: string | undefined;
    }

    /**
     * Threat intelligence and security information for the IP.
     */
    export interface Security {
        /** Aggregate risk score from 0 to 100. */
        threat_score: number;
        /** true if the IP matches a Tor exit node. */
        is_tor: boolean;
        /** true if the IP is associated with a proxy service. */
        is_proxy: boolean;
        /** Detected proxy provider names. */
        proxy_provider_names?: string[] | undefined;
        /** Proxy detection confidence from 0 to 100. */
        proxy_confidence_score: number;
        /** Last observed proxy activity date in YYYY-MM-DD. */
        proxy_last_seen?: string | undefined;
        /** true if the IP is linked to a residential proxy network. */
        is_residential_proxy: boolean;
        /** true if the IP is associated with a VPN service. */
        is_vpn: boolean;
        /** Detected VPN provider names. */
        vpn_provider_names?: string[] | undefined;
        /** VPN detection confidence from 0 to 100. */
        vpn_confidence_score: number;
        /** Last observed VPN activity date in YYYY-MM-DD. */
        vpn_last_seen?: string | undefined;
        /** true if the IP is associated with a relay network. */
        is_relay: boolean;
        /** Relay provider name. */
        relay_provider_name?: string | undefined;
        /** true if any anonymity signal is present. */
        is_anonymous: boolean;
        /** true if the IP is flagged for known attacker behavior. */
        is_known_attacker: boolean;
        /** true if the IP is associated with bot activity. */
        is_bot: boolean;
        /** true if the IP is associated with spam activity. */
        is_spam: boolean;
        /** true if the IP belongs to a cloud provider range. */
        is_cloud_provider: boolean;
        /** Cloud provider name. */
        cloud_provider_name?: string | undefined;
    }

    /**
     * Abuse contact information for the IP.
     */
    export interface Abuse {
        /** Abuse-handling IP range in CIDR notation. */
        route?: string | undefined;
        /** ISO 3166-1 alpha-2 country code of the abuse contact. */
        country?: string | undefined;
        /** Display name for the abuse contact. */
        name?: string | undefined;
        /** Organization name for the abuse contact. */
        organization?: string | undefined;
        /** Contact type: group or individual. */
        kind?: string | undefined;
        /** Registered address of the organization owning the IP. */
        address?: string | undefined;
        /** Abuse contact email addresses. */
        emails?: string[] | undefined;
        /** Abuse contact phone numbers. */
        phone_numbers?: string[] | undefined;
    }

    /**
     * Time zone information for the IP's location.
     */
    export interface TimeZone {
        /** Time zone in IANA TZDB format. */
        name: string;
        /** Standard time UTC offset in hours. */
        offset: number;
        /** Current effective UTC offset in hours, including DST. */
        offset_with_dst: number;
        /** Local date/time in YYYY-MM-DD HH:mm:ss.SSS±ZZZZ format. */
        current_time: string;
        /** Local time as Unix epoch seconds. */
        current_time_unix: number;
        /** Current time zone abbreviation. */
        current_tz_abbreviation?: string | undefined;
        /** Current time zone full name. */
        current_tz_full_name?: string | undefined;
        /** Standard (non-DST) abbreviation. */
        standard_tz_abbreviation?: string | undefined;
        /** Standard (non-DST) full name. */
        standard_tz_full_name?: string | undefined;
        /** true if DST is active. */
        is_dst: boolean;
        /** DST shift amount in hours. */
        dst_savings: number;
        /** true if the time zone observes DST. */
        dst_exists: boolean;
        /** DST abbreviation when DST is active. */
        dst_tz_abbreviation?: string | undefined;
        /** DST full name when DST is active. */
        dst_tz_full_name?: string | undefined;
        /** DST transition details (used for both the DST start and DST end transitions). */
        dst_start?: TimeZone.DstStart | undefined;
        /** DST transition details (used for both the DST start and DST end transitions). */
        dst_end?: TimeZone.DstEnd | undefined;
    }

    export namespace TimeZone {
        /**
         * DST transition details (used for both the DST start and DST end transitions).
         */
        export interface DstStart {
            /** DST transition moment in UTC. */
            utc_time?: string | undefined;
            /** Clock change at the DST transition, in hours. */
            duration?: string | undefined;
            /** true if local time jumps forward (some times do not exist). */
            gap?: boolean | undefined;
            /** Local date/time immediately after the DST transition. */
            date_time_after?: string | undefined;
            /** Local date/time immediately before the DST transition. */
            date_time_before?: string | undefined;
            /** true if local times repeat around the DST transition. */
            overlap?: boolean | undefined;
        }

        /**
         * DST transition details (used for both the DST start and DST end transitions).
         */
        export interface DstEnd {
            /** DST transition moment in UTC. */
            utc_time?: string | undefined;
            /** Clock change at the DST transition, in hours. */
            duration?: string | undefined;
            /** true if local time jumps forward (some times do not exist). */
            gap?: boolean | undefined;
            /** Local date/time immediately after the DST transition. */
            date_time_after?: string | undefined;
            /** Local date/time immediately before the DST transition. */
            date_time_before?: string | undefined;
            /** true if local times repeat around the DST transition. */
            overlap?: boolean | undefined;
        }
    }

    /**
     * Parsed User-Agent details from the request.
     */
    export interface UserAgent {
        /** Raw User-Agent string used for parsing. */
        user_agent_string?: string | undefined;
        /** Detected user agent product name. */
        name?: string | undefined;
        /** User agent category (e.g., Browser, Mobile App, Bot). */
        type?: string | undefined;
        /** Full product version string. */
        version?: string | undefined;
        /** Major version extracted from version. */
        version_major?: string | undefined;
        /** Device details. */
        device?: UserAgent.Device | undefined;
        /** Rendering engine details. */
        engine?: UserAgent.Engine | undefined;
        /** Operating system details. */
        operating_system?: UserAgent.OperatingSystem | undefined;
    }

    export namespace UserAgent {
        /**
         * Device details.
         */
        export interface Device {
            /** Detected device label. */
            name?: string | undefined;
            /** Device category (Desktop, Mobile, Tablet, Bot). */
            type?: string | undefined;
            /** Device vendor/brand. */
            brand?: string | undefined;
            /** CPU / architecture string. */
            cpu?: string | undefined;
        }

        /**
         * Rendering engine details.
         */
        export interface Engine {
            /** Rendering engine name. */
            name?: string | undefined;
            /** Engine category. */
            type?: string | undefined;
            /** Full engine version string. */
            version?: string | undefined;
            /** Major engine version. */
            version_major?: string | undefined;
        }

        /**
         * Operating system details.
         */
        export interface OperatingSystem {
            /** Operating system name. */
            name?: string | undefined;
            /** OS category (Desktop, Mobile, Server). */
            type?: string | undefined;
            /** OS version string. */
            version?: string | undefined;
            /** Major OS version. */
            version_major?: string | undefined;
            /** OS build identifier. */
            build?: string | undefined;
        }
    }
}
