// This file was auto-generated by Fern from our API Definition.

export interface GeolocationLookupV2Response {
    /** The IP address */
    ip?: string | undefined;
    /** The hostname (included when `hostname`, `liveHostname` or `hostnameFallbackLive` is requested) */
    hostname?: string | undefined;
    /** The domain name (returned when the lookup was performed for a domain) */
    domain?: string | undefined;
    location?: GeolocationLookupV2Response.Location | undefined;
    country_metadata?: GeolocationLookupV2Response.CountryMetadata | undefined;
    network?: GeolocationLookupV2Response.Network | undefined;
    currency?: GeolocationLookupV2Response.Currency | undefined;
    asn?: GeolocationLookupV2Response.Asn | undefined;
    company?: GeolocationLookupV2Response.Company | undefined;
    time_zone?: GeolocationLookupV2Response.TimeZone | undefined;
    user_agent?: GeolocationLookupV2Response.UserAgent | undefined;
    security?: GeolocationLookupV2Response.Security | undefined;
    abuse?: GeolocationLookupV2Response.Abuse | undefined;
}

export namespace GeolocationLookupV2Response {
    export interface Location {
        continent_code?: string | undefined;
        continent_name?: string | undefined;
        country_code2?: string | undefined;
        country_code3?: string | undefined;
        country_name?: string | undefined;
        country_name_official?: string | undefined;
        country_capital?: string | undefined;
        state_prov?: string | undefined;
        state_code?: string | undefined;
        district?: string | undefined;
        city?: string | undefined;
        locality?: string | undefined;
        zipcode?: string | undefined;
        latitude?: string | undefined;
        longitude?: string | undefined;
        is_eu?: boolean | undefined;
        country_flag?: string | undefined;
        geoname_id?: string | undefined;
        country_emoji?: string | undefined;
        /** Approximate radius (in km) around the location. Included when `geo_accuracy` is requested. */
        accuracy_radius?: string | undefined;
        /** Confidence level of the location result (high/medium/low). Included when `geo_accuracy` is requested. */
        confidence?: string | undefined;
        /** Designated Market Area code (USA only). Included when `dma_code` is requested. */
        dma_code?: string | undefined;
    }

    export interface CountryMetadata {
        /** The calling code of the country */
        calling_code?: string | undefined;
        /** The top level domain of the country */
        tld?: string | undefined;
        /** The languages spoken in the country */
        languages?: string[] | undefined;
    }

    export interface Network {
        /** The type of the connection */
        connection_type?: string | undefined;
        /** The network route/CIDR the IP belongs to */
        route?: string | undefined;
        /** Whether the IP is announced from multiple locations (anycast) */
        is_anycast?: boolean | undefined;
    }

    export interface Currency {
        code?: string | undefined;
        name?: string | undefined;
        symbol?: string | undefined;
    }

    export interface Asn {
        /** The AS number */
        as_number?: string | undefined;
        /** The organization name */
        organization?: string | undefined;
        /** The country code */
        country?: string | undefined;
        /** The type of the ASN */
        type?: string | undefined;
        /** The domain associated with the ASN */
        domain?: string | undefined;
        /** The date when the ASN was allocated */
        date_allocated?: string | undefined;
        /** The Regional Internet Registry (RIR) of the ASN */
        rir?: string | undefined;
    }

    export interface Company {
        /** The name of the company */
        name?: string | undefined;
        /** The type of the company */
        type?: string | undefined;
        /** The domain associated with the company */
        domain?: string | undefined;
    }

    export interface TimeZone {
        name?: string | undefined;
        offset?: number | undefined;
        offset_with_dst?: number | undefined;
        current_time?: string | undefined;
        current_time_unix?: number | undefined;
        current_tz_abbreviation?: string | undefined;
        current_tz_full_name?: string | undefined;
        standard_tz_abbreviation?: string | undefined;
        standard_tz_full_name?: string | undefined;
        is_dst?: boolean | undefined;
        dst_savings?: number | undefined;
        dst_exists?: boolean | undefined;
        dst_tz_abbreviation?: string | undefined;
        dst_tz_full_name?: string | undefined;
        dst_start?: TimeZone.DstStart | undefined;
        dst_end?: TimeZone.DstEnd | undefined;
    }

    export namespace TimeZone {
        export interface DstStart {
            utc_time?: string | undefined;
            duration?: string | undefined;
            gap?: boolean | undefined;
            date_time_after?: string | undefined;
            date_time_before?: string | undefined;
            overlap?: boolean | undefined;
        }

        export interface DstEnd {
            utc_time?: string | undefined;
            duration?: string | undefined;
            gap?: boolean | undefined;
            date_time_after?: string | undefined;
            date_time_before?: string | undefined;
            overlap?: boolean | undefined;
        }
    }

    export interface UserAgent {
        user_agent_string?: string | undefined;
        name?: string | undefined;
        type?: string | undefined;
        version?: string | undefined;
        version_major?: string | undefined;
        device?: UserAgent.Device | undefined;
        engine?: UserAgent.Engine | undefined;
        operating_system?: UserAgent.OperatingSystem | undefined;
    }

    export namespace UserAgent {
        export interface Device {
            name?: string | undefined;
            type?: string | undefined;
            brand?: string | undefined;
            cpu?: string | undefined;
        }

        export interface Engine {
            name?: string | undefined;
            type?: string | undefined;
            version?: string | undefined;
            version_major?: string | undefined;
        }

        export interface OperatingSystem {
            name?: string | undefined;
            type?: string | undefined;
            version?: string | undefined;
            version_major?: string | undefined;
            build?: string | undefined;
        }
    }

    export interface Security {
        threat_score?: number | undefined;
        is_tor?: boolean | undefined;
        is_proxy?: boolean | undefined;
        proxy_provider_names?: string[] | undefined;
        proxy_confidence_score?: number | undefined;
        proxy_last_seen?: string | undefined;
        is_residential_proxy?: boolean | undefined;
        is_vpn?: boolean | undefined;
        vpn_provider_names?: string[] | undefined;
        vpn_confidence_score?: number | undefined;
        vpn_last_seen?: string | undefined;
        is_relay?: boolean | undefined;
        relay_provider_name?: string | undefined;
        is_anonymous?: boolean | undefined;
        is_known_attacker?: boolean | undefined;
        is_bot?: boolean | undefined;
        is_spam?: boolean | undefined;
        is_cloud_provider?: boolean | undefined;
        cloud_provider_name?: string | undefined;
    }

    export interface Abuse {
        /** The IP range of the abuse contact */
        route?: string | undefined;
        /** The country of the abuse contact */
        country?: string | undefined;
        /** The name of the abuse contact */
        name?: string | undefined;
        /** The organization of the abuse contact */
        organization?: string | undefined;
        /** The kind of the abuse contact */
        kind?: string | undefined;
        /** The address of the abuse contact */
        address?: string | undefined;
        /** The list of email addresses of the abuse contact */
        emails?: string[] | undefined;
        /** The list of phone numbers of the abuse contact */
        phone_numbers?: string[] | undefined;
    }
}
