// This file was auto-generated by Fern from our API Definition.

export const GetAdminUnitDetailsRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type GetAdminUnitDetailsRequestFormat =
    (typeof GetAdminUnitDetailsRequestFormat)[keyof typeof GetAdminUnitDetailsRequestFormat];
