// This file was auto-generated by Fern from our API Definition.

export const GetAdminUnitsRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type GetAdminUnitsRequestFormat = (typeof GetAdminUnitsRequestFormat)[keyof typeof GetAdminUnitsRequestFormat];
