// This file was auto-generated by Fern from our API Definition.

export const GetAdminLevelsRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type GetAdminLevelsRequestFormat =
    (typeof GetAdminLevelsRequestFormat)[keyof typeof GetAdminLevelsRequestFormat];
