// This file was auto-generated by Fern from our API Definition.

export interface GetAdminUnitDetailsResponse {
    name: string;
    admin_code: string;
    admin_level: string;
    admin_iso3166_2: string;
    country_iso3166_2: string;
    country_name: string;
}
