// This file was auto-generated by Fern from our API Definition.

export interface GetAdminUnitsResponse {
    admin_units: GetAdminUnitsResponse.AdminUnits.Item[];
}

export namespace GetAdminUnitsResponse {
    export type AdminUnits = AdminUnits.Item[];

    export namespace AdminUnits {
        export interface Item {
            name: string;
            admin_code: string;
            admin_level: string;
        }
    }
}
