// This file was auto-generated by Fern from our API Definition.

export interface GetCitiesResponse {
    cities: GetCitiesResponse.Cities.Item[];
}

export namespace GetCitiesResponse {
    export type Cities = Cities.Item[];

    export namespace Cities {
        export interface Item {
            name: string;
            latitude: number;
            longitude: number;
            admin_unit: Item.AdminUnit;
            iso_alpha_2: string;
        }

        export namespace Item {
            export interface AdminUnit {
                name: string;
                admin_code: string;
                admin_level: string;
            }
        }
    }
}
