// This file was auto-generated by Fern from our API Definition.

export const GetCitiesRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type GetCitiesRequestFormat = (typeof GetCitiesRequestFormat)[keyof typeof GetCitiesRequestFormat];
