// This file was auto-generated by Fern from our API Definition.

export interface GetCountriesResponse {
    countries: GetCountriesResponse.Countries.Item[];
}

export namespace GetCountriesResponse {
    export type Countries = Countries.Item[];

    export namespace Countries {
        export interface Item {
            name: string;
            iso_alpha_2: string;
            iso_alpha_3: string;
            iso_numeric: number;
            capital: string;
            region: string;
            subregion: string;
        }
    }
}
