// This file was auto-generated by Fern from our API Definition.

export const GetCountriesRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type GetCountriesRequestFormat = (typeof GetCountriesRequestFormat)[keyof typeof GetCountriesRequestFormat];
