// This file was auto-generated by Fern from our API Definition.

export const GetCountryDetailsRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type GetCountryDetailsRequestFormat =
    (typeof GetCountryDetailsRequestFormat)[keyof typeof GetCountryDetailsRequestFormat];
