// This file was auto-generated by Fern from our API Definition.

export const GetFlagsRequestSize = {
    SixteenPx: "16px",
    TwentyFourPx: "24px",
    ThirtyTwoPx: "32px",
    FortyEightPx: "48px",
    SixtyFourPx: "64px",
} as const;
export type GetFlagsRequestSize = (typeof GetFlagsRequestSize)[keyof typeof GetFlagsRequestSize];
