// This file was auto-generated by Fern from our API Definition.

export const GetFlagsRequestShape = {
    Flat: "flat",
    Round: "round",
} as const;
export type GetFlagsRequestShape = (typeof GetFlagsRequestShape)[keyof typeof GetFlagsRequestShape];
