// This file was auto-generated by Fern from our API Definition.

export const GetFlagsRequestType = {
    Country: "country",
    Organization: "organization",
} as const;
export type GetFlagsRequestType = (typeof GetFlagsRequestType)[keyof typeof GetFlagsRequestType];
