// This file was auto-generated by Fern from our API Definition.

export const GetFlagsRequestFormat = {
    Png: "png",
    Webp: "webp",
    Svg: "svg",
} as const;
export type GetFlagsRequestFormat = (typeof GetFlagsRequestFormat)[keyof typeof GetFlagsRequestFormat];
