// This file was auto-generated by Fern from our API Definition.

export const GetRegionsRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type GetRegionsRequestFormat = (typeof GetRegionsRequestFormat)[keyof typeof GetRegionsRequestFormat];
