// This file was auto-generated by Fern from our API Definition.

export const GetSubregionsRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type GetSubregionsRequestFormat = (typeof GetSubregionsRequestFormat)[keyof typeof GetSubregionsRequestFormat];
