// This file was auto-generated by Fern from our API Definition.

export interface GrammarDetectResponse {
    /** List of words flagged as grammatically incorrect */
    grammar_errors: GrammarDetectResponse.GrammarErrors.Item[];
}

export namespace GrammarDetectResponse {
    export type GrammarErrors = GrammarErrors.Item[];

    export namespace GrammarErrors {
        export interface Item {
            /** The flagged word */
            word: string;
            /** Zero-based word position in the input text */
            offset: number;
        }
    }
}
