// This file was auto-generated by Fern from our API Definition.

export const HistoricalWeatherRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type HistoricalWeatherRequestFormat =
    (typeof HistoricalWeatherRequestFormat)[keyof typeof HistoricalWeatherRequestFormat];
