// This file was auto-generated by Fern from our API Definition.

export const HistoricalWeatherRequestPrecision = {
    Daily: "daily",
    Hourly: "hourly",
} as const;
export type HistoricalWeatherRequestPrecision =
    (typeof HistoricalWeatherRequestPrecision)[keyof typeof HistoricalWeatherRequestPrecision];
