// This file was auto-generated by Fern from our API Definition.

export const IbanValidateRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type IbanValidateRequestFormat = (typeof IbanValidateRequestFormat)[keyof typeof IbanValidateRequestFormat];
