// This file was auto-generated by Fern from our API Definition.

export interface IpSecurityLookupResponse {
    ip?: string | undefined;
    security?: IpSecurityLookupResponse.Security | undefined;
}

export namespace IpSecurityLookupResponse {
    export interface Security {
        threat_score?: number | undefined;
        is_tor?: boolean | undefined;
        is_proxy?: boolean | undefined;
        proxy_provider_names?: string[] | undefined;
        proxy_confidence_score?: number | undefined;
        proxy_last_seen?: string | undefined;
        is_residential_proxy?: boolean | undefined;
        is_vpn?: boolean | undefined;
        vpn_provider_names?: string[] | undefined;
        vpn_confidence_score?: number | undefined;
        vpn_last_seen?: string | undefined;
        is_relay?: boolean | undefined;
        relay_provider_name?: string | undefined;
        is_anonymous?: boolean | undefined;
        is_known_attacker?: boolean | undefined;
        is_bot?: boolean | undefined;
        is_spam?: boolean | undefined;
        is_cloud_provider?: boolean | undefined;
        cloud_provider_name?: string | undefined;
    }
}
