// This file was auto-generated by Fern from our API Definition.

export const IpSecurityLookupRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type IpSecurityLookupRequestFormat =
    (typeof IpSecurityLookupRequestFormat)[keyof typeof IpSecurityLookupRequestFormat];
