// This file was auto-generated by Fern from our API Definition.

export const IpWhoisLookupRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type IpWhoisLookupRequestFormat = (typeof IpWhoisLookupRequestFormat)[keyof typeof IpWhoisLookupRequestFormat];
