// This file was auto-generated by Fern from our API Definition.

export const MarineWeatherRequestPrecision = {
    Daily: "daily",
    Hourly: "hourly",
    Minutely: "minutely",
} as const;
export type MarineWeatherRequestPrecision =
    (typeof MarineWeatherRequestPrecision)[keyof typeof MarineWeatherRequestPrecision];
