// This file was auto-generated by Fern from our API Definition.

export const MarineWeatherRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type MarineWeatherRequestFormat = (typeof MarineWeatherRequestFormat)[keyof typeof MarineWeatherRequestFormat];
