// This file was auto-generated by Fern from our API Definition.

export const PdfConvertToPngRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type PdfConvertToPngRequestFormat =
    (typeof PdfConvertToPngRequestFormat)[keyof typeof PdfConvertToPngRequestFormat];
