// This file was auto-generated by Fern from our API Definition.

export const PdfConvertToPngRequestProfile = {
    Bw: "bw",
    Gray: "gray",
    Rgb: "rgb",
    Rgba: "rgba",
    FourBit: "4-bit",
    EightBit: "8-bit",
} as const;
export type PdfConvertToPngRequestProfile =
    (typeof PdfConvertToPngRequestProfile)[keyof typeof PdfConvertToPngRequestProfile];
