// This file was auto-generated by Fern from our API Definition.

export const PdfConvertToTiffRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type PdfConvertToTiffRequestFormat =
    (typeof PdfConvertToTiffRequestFormat)[keyof typeof PdfConvertToTiffRequestFormat];
