// This file was auto-generated by Fern from our API Definition.

export const PdfConvertToTiffRequestProfile = {
    Bw: "bw",
    Gray: "gray",
    Rgb: "rgb",
    Rgba: "rgba",
    Cmyk: "cmyk",
} as const;
export type PdfConvertToTiffRequestProfile =
    (typeof PdfConvertToTiffRequestProfile)[keyof typeof PdfConvertToTiffRequestProfile];
