// This file was auto-generated by Fern from our API Definition.

export const PdfConvertToJpgRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type PdfConvertToJpgRequestFormat =
    (typeof PdfConvertToJpgRequestFormat)[keyof typeof PdfConvertToJpgRequestFormat];
