// This file was auto-generated by Fern from our API Definition.

export const PdfConvertToGifRequestProfile = {
    Bw: "bw",
    Gray: "gray",
    Rgb: "rgb",
    Rgba: "rgba",
    FourBit: "4-bit",
    EightBit: "8-bit",
} as const;
export type PdfConvertToGifRequestProfile =
    (typeof PdfConvertToGifRequestProfile)[keyof typeof PdfConvertToGifRequestProfile];
