// This file was auto-generated by Fern from our API Definition.

export const PdfConvertToGifRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type PdfConvertToGifRequestFormat =
    (typeof PdfConvertToGifRequestFormat)[keyof typeof PdfConvertToGifRequestFormat];
