// This file was auto-generated by Fern from our API Definition.

export const PdfCompressRequestCompressionLevel = {
    Low: "low",
    Balanced: "balanced",
    High: "high",
    Extreme: "extreme",
} as const;
export type PdfCompressRequestCompressionLevel =
    (typeof PdfCompressRequestCompressionLevel)[keyof typeof PdfCompressRequestCompressionLevel];
