// This file was auto-generated by Fern from our API Definition.

export const PdfConvertToBmpRequestProfile = {
    Bw: "bw",
    Gray: "gray",
    Rgb: "rgb",
    FourBit: "4-bit",
    EightBit: "8-bit",
} as const;
export type PdfConvertToBmpRequestProfile =
    (typeof PdfConvertToBmpRequestProfile)[keyof typeof PdfConvertToBmpRequestProfile];
