// This file was auto-generated by Fern from our API Definition.

export const PdfCompressRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type PdfCompressRequestFormat = (typeof PdfCompressRequestFormat)[keyof typeof PdfCompressRequestFormat];
