// This file was auto-generated by Fern from our API Definition.

export const PdfConvertToBmpRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type PdfConvertToBmpRequestFormat =
    (typeof PdfConvertToBmpRequestFormat)[keyof typeof PdfConvertToBmpRequestFormat];
