// This file was auto-generated by Fern from our API Definition.

export const PdfConvertToJpgRequestProfile = {
    Gray: "gray",
    Rgb: "rgb",
    Cmyk: "cmyk",
} as const;
export type PdfConvertToJpgRequestProfile =
    (typeof PdfConvertToJpgRequestProfile)[keyof typeof PdfConvertToJpgRequestProfile];
