// This file was auto-generated by Fern from our API Definition.

export const PdfDeleteFileRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type PdfDeleteFileRequestFormat = (typeof PdfDeleteFileRequestFormat)[keyof typeof PdfDeleteFileRequestFormat];
