// This file was auto-generated by Fern from our API Definition.

export const PdfDownloadResourceRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type PdfDownloadResourceRequestFormat =
    (typeof PdfDownloadResourceRequestFormat)[keyof typeof PdfDownloadResourceRequestFormat];
