// This file was auto-generated by Fern from our API Definition.

export const PdfEncryptRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type PdfEncryptRequestFormat = (typeof PdfEncryptRequestFormat)[keyof typeof PdfEncryptRequestFormat];
