// This file was auto-generated by Fern from our API Definition.

export const PdfExtractPagesRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type PdfExtractPagesRequestFormat =
    (typeof PdfExtractPagesRequestFormat)[keyof typeof PdfExtractPagesRequestFormat];
