// This file was auto-generated by Fern from our API Definition.

export const PdfGetTaskStatusRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type PdfGetTaskStatusRequestFormat =
    (typeof PdfGetTaskStatusRequestFormat)[keyof typeof PdfGetTaskStatusRequestFormat];
