// This file was auto-generated by Fern from our API Definition.

export const PdfGetFileStatusRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type PdfGetFileStatusRequestFormat =
    (typeof PdfGetFileStatusRequestFormat)[keyof typeof PdfGetFileStatusRequestFormat];
