// This file was auto-generated by Fern from our API Definition.

export interface PdfListFilesResponse {
    files: PdfListFilesResponse.Files.Item[];
}

export namespace PdfListFilesResponse {
    export type Files = Files.Item[];

    export namespace Files {
        export interface Item {
            fileId: string;
            fileName: string;
            fileType?: string | undefined;
            fileCreationTime?: string | undefined;
            fileDeletionTime?: string | undefined;
        }
    }
}
