// This file was auto-generated by Fern from our API Definition.

export const PdfListFilesRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type PdfListFilesRequestFormat = (typeof PdfListFilesRequestFormat)[keyof typeof PdfListFilesRequestFormat];
