// This file was auto-generated by Fern from our API Definition.

export const PdfMergeRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type PdfMergeRequestFormat = (typeof PdfMergeRequestFormat)[keyof typeof PdfMergeRequestFormat];
