// This file was auto-generated by Fern from our API Definition.

export const PdfRestrictRequestRestrictionsItem = {
    PrintHigh: "print_high",
    PrintLow: "print_low",
    EditDocumentAssembly: "edit_document_assembly",
    FillFormFields: "fill_form_fields",
    EditAnnotations: "edit_annotations",
    ModifyContent: "modify_content",
    CopyAndExtractContent: "copy_and_extract_content",
    UseAccessibility: "use_accessibility",
} as const;
export type PdfRestrictRequestRestrictionsItem =
    (typeof PdfRestrictRequestRestrictionsItem)[keyof typeof PdfRestrictRequestRestrictionsItem];
