// This file was auto-generated by Fern from our API Definition.

export const PdfRotateRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type PdfRotateRequestFormat = (typeof PdfRotateRequestFormat)[keyof typeof PdfRotateRequestFormat];
