// This file was auto-generated by Fern from our API Definition.

export const PdfRestrictRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type PdfRestrictRequestFormat = (typeof PdfRestrictRequestFormat)[keyof typeof PdfRestrictRequestFormat];
