// This file was auto-generated by Fern from our API Definition.

export const PdfRemovePagesRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type PdfRemovePagesRequestFormat =
    (typeof PdfRemovePagesRequestFormat)[keyof typeof PdfRemovePagesRequestFormat];
