// This file was auto-generated by Fern from our API Definition.

export const PdfSplitRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type PdfSplitRequestFormat = (typeof PdfSplitRequestFormat)[keyof typeof PdfSplitRequestFormat];
