// This file was auto-generated by Fern from our API Definition.

export const PdfUploadResourcesRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type PdfUploadResourcesRequestFormat =
    (typeof PdfUploadResourcesRequestFormat)[keyof typeof PdfUploadResourcesRequestFormat];
