// This file was auto-generated by Fern from our API Definition.

export interface PdfUploadBinaryResponse {
    /** The name of the uploaded file. */
    fileName?: string | undefined;
    /** The unique identifier assigned to the uploaded file. */
    fileId: string;
}
