// This file was auto-generated by Fern from our API Definition.

export const PdfUploadBinaryRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type PdfUploadBinaryRequestFormat =
    (typeof PdfUploadBinaryRequestFormat)[keyof typeof PdfUploadBinaryRequestFormat];
