// This file was auto-generated by Fern from our API Definition.

export const PdfUnrestrictRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type PdfUnrestrictRequestFormat = (typeof PdfUnrestrictRequestFormat)[keyof typeof PdfUnrestrictRequestFormat];
