// This file was auto-generated by Fern from our API Definition.

export interface PdfUploadResourcesResponse {
    files: PdfUploadResourcesResponse.Files.Item[];
}

export namespace PdfUploadResourcesResponse {
    export type Files = Files.Item[];

    export namespace Files {
        export interface Item {
            fileName: string;
            fileId: string;
        }
    }
}
