// This file was auto-generated by Fern from our API Definition.

export const PhoneValidateRequestFormat = {
    Json: "json",
} as const;
export type PhoneValidateRequestFormat = (typeof PhoneValidateRequestFormat)[keyof typeof PhoneValidateRequestFormat];
