// This file was auto-generated by Fern from our API Definition.

export const ReadabilityScoreRequestTarget = {
    General: "general",
    Professional: "professional",
    Academic: "academic",
    Technical: "technical",
} as const;
export type ReadabilityScoreRequestTarget =
    (typeof ReadabilityScoreRequestTarget)[keyof typeof ReadabilityScoreRequestTarget];
