// This file was auto-generated by Fern from our API Definition.

export interface RequestTimeoutErrorBody {
    timestamp?: string | undefined;
    status?: number | undefined;
    error?: string | undefined;
    message?: string | undefined;
    path?: string | undefined;
}
