// This file was auto-generated by Fern from our API Definition.

export const ScreenshotCaptureRequestFileType = {
    Png: "PNG",
    Jpeg: "JPEG",
    Webp: "WEBP",
    Pdf: "PDF",
    Mp4: "mp4",
    Gif: "gif",
    Webm: "webm",
} as const;
export type ScreenshotCaptureRequestFileType =
    (typeof ScreenshotCaptureRequestFileType)[keyof typeof ScreenshotCaptureRequestFileType];
