// This file was auto-generated by Fern from our API Definition.

export const ScreenshotCaptureRequestWaitForEvent = {
    Load: "load",
    Domcontentloaded: "domcontentloaded",
    Networkidle: "networkidle",
} as const;
export type ScreenshotCaptureRequestWaitForEvent =
    (typeof ScreenshotCaptureRequestWaitForEvent)[keyof typeof ScreenshotCaptureRequestWaitForEvent];
