// This file was auto-generated by Fern from our API Definition.

export const ScreenshotCaptureRequestOutput = {
    Json: "json",
    Image: "image",
} as const;
export type ScreenshotCaptureRequestOutput =
    (typeof ScreenshotCaptureRequestOutput)[keyof typeof ScreenshotCaptureRequestOutput];
