// This file was auto-generated by Fern from our API Definition.

export const ScreenshotCaptureRequestScrollSpeed = {
    Normal: "normal",
    Fast: "fast",
    Slow: "slow",
} as const;
export type ScreenshotCaptureRequestScrollSpeed =
    (typeof ScreenshotCaptureRequestScrollSpeed)[keyof typeof ScreenshotCaptureRequestScrollSpeed];
