// This file was auto-generated by Fern from our API Definition.

export const SubdomainsLookupRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type SubdomainsLookupRequestFormat =
    (typeof SubdomainsLookupRequestFormat)[keyof typeof SubdomainsLookupRequestFormat];
