// This file was auto-generated by Fern from our API Definition.

export const SubdomainsLookupRequestStatus = {
    Active: "active",
    Inactive: "inactive",
} as const;
export type SubdomainsLookupRequestStatus =
    (typeof SubdomainsLookupRequestStatus)[keyof typeof SubdomainsLookupRequestStatus];
