// This file was auto-generated by Fern from our API Definition.

export const SwiftCodeLookupRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type SwiftCodeLookupRequestFormat =
    (typeof SwiftCodeLookupRequestFormat)[keyof typeof SwiftCodeLookupRequestFormat];
