// This file was auto-generated by Fern from our API Definition.

export interface SwiftCodeLookupResponse {
    swiftCode: string;
    countryCode: string;
    bankAddress: string;
    bankCode: string;
    bankName: string;
    city: string;
    country: string;
}
