// This file was auto-generated by Fern from our API Definition.

export const SwiftCodeFindRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type SwiftCodeFindRequestFormat = (typeof SwiftCodeFindRequestFormat)[keyof typeof SwiftCodeFindRequestFormat];
