// This file was auto-generated by Fern from our API Definition.

export interface TimezoneConvertResponse {
    /** Original time before conversion (format YYYY-MM-DD HH:mm:ss, not ISO 8601). */
    original_time: string;
    /** Time after conversion (format YYYY-MM-DD HH:mm:ss, not ISO 8601). */
    converted_time: string;
    /** Difference in hours */
    diff_hour: number;
    /** Difference in minutes */
    diff_min: number;
}
