// This file was auto-generated by Fern from our API Definition.

/**
 * Timezone lookup result. time_zone is always present. Exactly which other object accompanies it depends on the lookup mode: tz name and lat/long coordinates return time_zone only (no location, no ip); location address returns a basic location object; ip param or client-IP fallback returns a rich location object plus top-level ip; iata_code/icao_code returns airport_details instead of location; lo_code returns lo_code_details instead of location.
 */
export interface TimezoneLookupV2Response {
    /** The IP address used for the timezone lookup. Present when queried using the ip parameter, or with no location-identifying parameter at all (client-IP fallback). Absent for every other lookup mode. */
    ip?: string | undefined;
    /** Timezone and date/time information for the location. */
    time_zone: TimezoneLookupV2Response.TimeZone;
    /** Geographic location information. Only present for location (address) and ip (or client-IP fallback) lookups; absent for tz, lat/long, iata_code/icao_code, and lo_code lookups. Field set varies by mode: location returns location_string plus a basic field set (country_name, state_prov, city, locality, latitude, longitude); ip/default returns a richer geo-IP field set (continent_code, continent_name, country_code2, country_code3, country_name_official, is_eu, state_code, district, zipcode) plus the common fields, but never location_string or locality. */
    location?: TimezoneLookupV2Response.Location | undefined;
    /** Airport information, present when queried by IATA or ICAO code. */
    airport_details?: TimezoneLookupV2Response.AirportDetails | undefined;
    /** UN/LOCODE location details, present when queried by LO code. */
    lo_code_details?: TimezoneLookupV2Response.LoCodeDetails | undefined;
}

export namespace TimezoneLookupV2Response {
    /**
     * Timezone and date/time information for the location.
     */
    export interface TimeZone {
        /** The IANA timezone name/identifier for the location. */
        name: string;
        /** The Standard time zone offset from UTC in hours. */
        offset: number;
        /** The time zone offset from UTC in hours, accounting for DST. */
        offset_with_dst: number;
        /** The current date and time with timezone offset in YYYY-MM-DD HH:mm:ss.SSS±ZZZZ format. */
        current_time: string;
        /** The Unix timestamp representing the date and time in seconds. */
        current_time_unix: number;
        /** The current date in YYYY-MM-DD format. */
        date: string;
        /** The current date and time in YYYY-MM-DD HH:mm:ss format. */
        date_time: string;
        /** The current date and time in descriptive format EEEE, MMMM dd, yyyy HH:mm:ss. */
        date_time_txt: string;
        /** The date and time with time zone information in EEE, dd MMM yyyy HH:mm:ss Z format. */
        date_time_wti: string;
        /** The date and time with timezone offset in ISO 8601 format YYYY-MM-DDTHH:mm:ss±HHMM. */
        date_time_ymd: string;
        /** The current time in 24-hour format HH:mm:ss. */
        time_24: string;
        /** The current time in 12-hour format with AM/PM notation. */
        time_12: string;
        /** The week number of the year (1-52). */
        week: number;
        /** The current month as a number (1-12). */
        month: number;
        /** The four-digit current year. */
        year: number;
        /** The two-digit abbreviation for the year. */
        year_abbr: string;
        /** Abbreviation of the time zone currently in effect (standard or DST). */
        current_tz_abbreviation: string;
        /** Full name of the time zone currently in effect. */
        current_tz_full_name: string;
        /** Abbreviation of the standard (non-DST) time zone. */
        standard_tz_abbreviation: string;
        /** Full name of the standard (non-DST) time zone. */
        standard_tz_full_name: string;
        /** Is the time zone in daylight savings? */
        is_dst: boolean;
        /** Abbreviation of the DST time zone. Always present as a key; holds an empty string when dst_exists is false. */
        dst_tz_abbreviation?: string | undefined;
        /** Full name of the DST time zone. Always present as a key; holds an empty string when dst_exists is false. */
        dst_tz_full_name?: string | undefined;
        /** The amount of time added for daylight saving in hours. */
        dst_savings: number;
        /** Indicates whether DST is observed in the region. */
        dst_exists: boolean;
        /** DST transition details (used for both the DST start and DST end transitions). Always present as a key on the parent TimeZone object; returned as an empty object {} when dst_exists is false, so none of its properties are required. */
        dst_start?: TimeZone.DstStart | undefined;
        /** DST transition details (used for both the DST start and DST end transitions). Always present as a key on the parent TimeZone object; returned as an empty object {} when dst_exists is false, so none of its properties are required. */
        dst_end?: TimeZone.DstEnd | undefined;
    }

    export namespace TimeZone {
        /**
         * DST transition details (used for both the DST start and DST end transitions). Always present as a key on the parent TimeZone object; returned as an empty object {} when dst_exists is false, so none of its properties are required.
         */
        export interface DstStart {
            /** DST transition moment in UTC. */
            utc_time?: string | undefined;
            /** Clock change at the DST transition, in hours. */
            duration?: string | undefined;
            /** true if local time jumps forward (some times do not exist). */
            gap?: boolean | undefined;
            /** Local date/time immediately after the DST transition. */
            date_time_after?: string | undefined;
            /** Local date/time immediately before the DST transition. */
            date_time_before?: string | undefined;
            /** true if local times repeat around the DST transition. */
            overlap?: boolean | undefined;
        }

        /**
         * DST transition details (used for both the DST start and DST end transitions). Always present as a key on the parent TimeZone object; returned as an empty object {} when dst_exists is false, so none of its properties are required.
         */
        export interface DstEnd {
            /** DST transition moment in UTC. */
            utc_time?: string | undefined;
            /** Clock change at the DST transition, in hours. */
            duration?: string | undefined;
            /** true if local time jumps forward (some times do not exist). */
            gap?: boolean | undefined;
            /** Local date/time immediately after the DST transition. */
            date_time_after?: string | undefined;
            /** Local date/time immediately before the DST transition. */
            date_time_before?: string | undefined;
            /** true if local times repeat around the DST transition. */
            overlap?: boolean | undefined;
        }
    }

    /**
     * Geographic location information. Only present for location (address) and ip (or client-IP fallback) lookups; absent for tz, lat/long, iata_code/icao_code, and lo_code lookups. Field set varies by mode: location returns location_string plus a basic field set (country_name, state_prov, city, locality, latitude, longitude); ip/default returns a richer geo-IP field set (continent_code, continent_name, country_code2, country_code3, country_name_official, is_eu, state_code, district, zipcode) plus the common fields, but never location_string or locality.
     */
    export interface Location {
        /** The provided location parameter as location. Present only for location (address) lookups; absent for ip lookups. */
        location_string?: string | undefined;
        /** The two-letter code of the continent (e.g., NA). Geo-IP field only: present for ip param or default client-IP lookups; absent for location lookups. */
        continent_code?: string | undefined;
        /** The full name of the continent (e.g., North America). Geo-IP field only: present for ip param or default client-IP lookups; absent for location lookups. */
        continent_name?: string | undefined;
        /** The ISO 3166-1 alpha-2 two-letter country code (e.g., US). Geo-IP field only: present for ip param or default client-IP lookups; absent for location lookups. */
        country_code2?: string | undefined;
        /** The ISO 3166-1 alpha-3 three-letter country code (e.g., USA). Geo-IP field only: present for ip param or default client-IP lookups; absent for location lookups. */
        country_code3?: string | undefined;
        /** The common name of the country (e.g., United States). Present for both location and ip lookups. */
        country_name?: string | undefined;
        /** The official full name of the country (e.g., United States of America). Geo-IP field only: present for ip param or default client-IP lookups; absent for location lookups. */
        country_name_official?: string | undefined;
        /** Whether the country belongs to the European Union. Geo-IP field only: present for ip param or default client-IP lookups; absent for location lookups. */
        is_eu?: boolean | undefined;
        /** Name of the state/province/region. Present for both location and ip lookups. */
        state_prov?: string | undefined;
        /** Code of the state/province/region. Geo-IP field only: present for ip param or default client-IP lookups; absent for location lookups. */
        state_code?: string | undefined;
        /** Name of the district or county. Geo-IP field only: present for ip param or default client-IP lookups; absent for location lookups. */
        district?: string | undefined;
        /** Name of the city. Present for both location and ip lookups. */
        city?: string | undefined;
        /** Smaller area, part or region of a city. Only present for location (address) lookups (may be an empty string); absent for ip lookups. */
        locality?: string | undefined;
        /** ZIP/Postal code of the place. Geo-IP field only: present for ip param or default client-IP lookups; absent for location lookups. */
        zipcode?: string | undefined;
        /** The geographic latitude of the location. Present for both location and ip lookups. */
        latitude?: string | undefined;
        /** The geographic longitude of the location. Present for both location and ip lookups. */
        longitude?: string | undefined;
    }

    /**
     * Airport information, present when queried by IATA or ICAO code.
     */
    export interface AirportDetails {
        /** Classification of the airport based on size and traffic. */
        type?: string | undefined;
        /** The full name of the airport. */
        name?: string | undefined;
        /** The latitude coordinate of the airport. */
        latitude?: string | undefined;
        /** The longitude coordinate of the airport. */
        longitude?: string | undefined;
        /** The elevation of the airport above sea level, measured in feet. */
        elevation_ft?: number | undefined;
        /** The two-letter code of the continent. */
        continent_code?: string | undefined;
        /** The ISO 3166-1 alpha-2 code for the country where the airport is located. */
        country_code?: string | undefined;
        /** Code of the state/province/region where the airport is located. */
        state_code?: string | undefined;
        /** The city or administrative region that the airport serves. */
        city?: string | undefined;
        /** The three-letter IATA airport code (e.g., LHR). */
        iata_code?: string | undefined;
        /** The four-letter ICAO airport code (e.g., EGLL). */
        icao_code?: string | undefined;
        /** The FAA location identifier, used primarily in the United States. */
        faa_code?: string | undefined;
    }

    /**
     * UN/LOCODE location details, present when queried by LO code.
     */
    export interface LoCodeDetails {
        /** A unique identifier for the location, often used in logistics and shipping (e.g., USNYC). */
        lo_code?: string | undefined;
        /** The name of the city or location associated with the LO code. */
        city?: string | undefined;
        /** The code for the state, province or region. */
        state_code?: string | undefined;
        /** The ISO 3166-1 alpha-2 country code (e.g., US). */
        country_code?: string | undefined;
        /** The name of the country in an administrative context. */
        country_name?: string | undefined;
        /** The type of location as comma-separated list of facilities (e.g., Port, Rail Terminal, Road Terminal, Airport). */
        location_type?: string | undefined;
        /** The latitude coordinate of the location. */
        latitude?: string | undefined;
        /** The longitude coordinate of the location. */
        longitude?: string | undefined;
    }
}
