// This file was auto-generated by Fern from our API Definition.

export const TimezoneLookupRequestLang = {
    En: "en",
    De: "de",
    Ru: "ru",
    Ja: "ja",
    Fr: "fr",
    Cn: "cn",
    Es: "es",
    Cs: "cs",
    It: "it",
} as const;
export type TimezoneLookupRequestLang = (typeof TimezoneLookupRequestLang)[keyof typeof TimezoneLookupRequestLang];
