// This file was auto-generated by Fern from our API Definition.

export const TimezoneConvertRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type TimezoneConvertRequestFormat =
    (typeof TimezoneConvertRequestFormat)[keyof typeof TimezoneConvertRequestFormat];
