// This file was auto-generated by Fern from our API Definition.

export interface TimezoneLookupResponse {
    ip?: string | undefined;
    location?: TimezoneLookupResponse.Location | undefined;
    time_zone?: TimezoneLookupResponse.TimeZone | undefined;
    airport_detail?: TimezoneLookupResponse.AirportDetails | undefined;
    lo_code_details?: TimezoneLookupResponse.LoCodeDetails | undefined;
}

export namespace TimezoneLookupResponse {
    export interface Location {
        location_string?: string | undefined;
        country_name?: string | undefined;
        state_prov?: string | undefined;
        city?: string | undefined;
        locality?: string | undefined;
        latitude?: string | undefined;
        longitude?: string | undefined;
        continent_code?: string | undefined;
        continent_name?: string | undefined;
        country_code2?: string | undefined;
        country_code3?: string | undefined;
        country_name_official?: string | undefined;
        is_eu?: boolean | undefined;
        state_code?: string | undefined;
        district?: string | undefined;
        zipcode?: string | undefined;
        /** Accepts any additional properties */
        [key: string]: any;
    }

    export interface TimeZone {
        name: string;
        offset: number;
        offset_with_dst: number;
        date: string;
        date_time: string;
        date_time_txt: string;
        date_time_wti: string;
        date_time_ymd: string;
        date_time_unix: number;
        time_24: string;
        time_12: string;
        week: number;
        month: number;
        year: number;
        year_abbr: string;
        is_dst: boolean;
        dst_savings: number;
        dst_exists: boolean;
        dst_start: TimeZone.DstStart;
        dst_end: TimeZone.DstEnd;
        /** Accepts any additional properties */
        [key: string]: any;
    }

    export namespace TimeZone {
        export interface DstStart {
            utc_time?: string | undefined;
            duration?: string | undefined;
            gap?: boolean | undefined;
            date_time_after?: string | undefined;
            date_time_before?: string | undefined;
            overlap?: boolean | undefined;
            /** Accepts any additional properties */
            [key: string]: any;
        }

        export interface DstEnd {
            utc_time?: string | undefined;
            duration?: string | undefined;
            gap?: boolean | undefined;
            date_time_after?: string | undefined;
            date_time_before?: string | undefined;
            overlap?: boolean | undefined;
            /** Accepts any additional properties */
            [key: string]: any;
        }
    }

    export interface AirportDetails {
        type?: string | undefined;
        name?: string | undefined;
        longitude?: number | undefined;
        latitude?: number | undefined;
        elevation_ft?: number | undefined;
        continent_code?: string | undefined;
        country_code?: string | undefined;
        state_code?: string | undefined;
        city?: string | undefined;
        iata_code?: string | undefined;
        icao_code?: string | undefined;
        faa_code?: string | undefined;
    }

    export interface LoCodeDetails {
        lo_code?: string | undefined;
        city?: string | undefined;
        longitude?: number | undefined;
        latitude?: number | undefined;
        state_code?: string | undefined;
        country_code?: string | undefined;
        country_name?: string | undefined;
        location_type?: string | undefined;
    }
}
