// This file was auto-generated by Fern from our API Definition.

export const TimezoneLookupV2RequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type TimezoneLookupV2RequestFormat =
    (typeof TimezoneLookupV2RequestFormat)[keyof typeof TimezoneLookupV2RequestFormat];
