// This file was auto-generated by Fern from our API Definition.

export const UserAgentLookupRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type UserAgentLookupRequestFormat =
    (typeof UserAgentLookupRequestFormat)[keyof typeof UserAgentLookupRequestFormat];
