// This file was auto-generated by Fern from our API Definition.

export interface VatRateByCountryResponseItem {
    country: string;
    state?: string | undefined;
    type: string;
    currency: string;
    standard_rate: number;
    reduced_rate: number[];
    /** Optional super-reduced VAT rates applicable in specific categories. */
    super_reduced_rate?: number[] | undefined;
    parking_rate?: number | undefined;
    categories: Record<string, number>;
}
