// This file was auto-generated by Fern from our API Definition.

export const VatRateByIpRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type VatRateByIpRequestFormat = (typeof VatRateByIpRequestFormat)[keyof typeof VatRateByIpRequestFormat];
