// This file was auto-generated by Fern from our API Definition.

export const VatRateByCountryRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type VatRateByCountryRequestFormat =
    (typeof VatRateByCountryRequestFormat)[keyof typeof VatRateByCountryRequestFormat];
