// This file was auto-generated by Fern from our API Definition.

export const VatSupportedCountriesRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type VatSupportedCountriesRequestFormat =
    (typeof VatSupportedCountriesRequestFormat)[keyof typeof VatSupportedCountriesRequestFormat];
