// This file was auto-generated by Fern from our API Definition.

export interface VatSupportedCountriesResponse {
    VAT_Supported_Countries_And_States?:
        | VatSupportedCountriesResponse.VatSupportedCountriesAndStates.Item[]
        | undefined;
}

export namespace VatSupportedCountriesResponse {
    export type VatSupportedCountriesAndStates = VatSupportedCountriesAndStates.Item[];

    export namespace VatSupportedCountriesAndStates {
        export interface Item {
            code: string;
            name: string;
            states: string[];
        }
    }
}
