// This file was auto-generated by Fern from our API Definition.

export const VatSupportedCountriesRequestType = {
    Iban: "IBAN",
    Swift: "SWIFT",
    Vat: "VAT",
} as const;
export type VatSupportedCountriesRequestType =
    (typeof VatSupportedCountriesRequestType)[keyof typeof VatSupportedCountriesRequestType];
