// This file was auto-generated by Fern from our API Definition.

export const VatValidateRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type VatValidateRequestFormat = (typeof VatValidateRequestFormat)[keyof typeof VatValidateRequestFormat];
