// This file was auto-generated by Fern from our API Definition.

export interface VatValidateResponse {
    country_code: string;
    vat_number: string;
    requester_country_code?: string | undefined;
    requester_vat_number?: string | undefined;
    requested_at: string;
    validation: VatValidateResponse.Validation;
    company: VatValidateResponse.Company;
}

export namespace VatValidateResponse {
    export interface Validation {
        is_valid: boolean;
        /** Returned when the upstream authority provides a consultation reference. */
        consultation_number?: string | undefined;
        consultation_authority: string;
    }

    export interface Company {
        company_name: string;
        company_address: string;
    }
}
