// This file was auto-generated by Fern from our API Definition.

export interface WeakWordsDetectResponse {
    /** List of detected weak words */
    weak_words: WeakWordsDetectResponse.WeakWords.Item[];
}

export namespace WeakWordsDetectResponse {
    export type WeakWords = WeakWords.Item[];

    export namespace WeakWords {
        export interface Item {
            /** The detected weak word */
            word: string;
            /** Zero-based word position in the input text */
            offset: number;
        }
    }
}
