// This file was auto-generated by Fern from our API Definition.

export const WeatherForecastRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type WeatherForecastRequestFormat =
    (typeof WeatherForecastRequestFormat)[keyof typeof WeatherForecastRequestFormat];
