// This file was auto-generated by Fern from our API Definition.

export const WeatherTimeSeriesRequestPrecision = {
    Daily: "daily",
    Hourly: "hourly",
} as const;
export type WeatherTimeSeriesRequestPrecision =
    (typeof WeatherTimeSeriesRequestPrecision)[keyof typeof WeatherTimeSeriesRequestPrecision];
