// This file was auto-generated by Fern from our API Definition.

export const WeatherTimeSeriesRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type WeatherTimeSeriesRequestFormat =
    (typeof WeatherTimeSeriesRequestFormat)[keyof typeof WeatherTimeSeriesRequestFormat];
