// This file was auto-generated by Fern from our API Definition.

export const WeatherForecastRequestPrecision = {
    Daily: "daily",
    Hourly: "hourly",
    Minutely: "minutely",
} as const;
export type WeatherForecastRequestPrecision =
    (typeof WeatherForecastRequestPrecision)[keyof typeof WeatherForecastRequestPrecision];
