// This file was auto-generated by Fern from our API Definition.

export const WebScrapeRequestFormat = {
    Json: "json",
} as const;
export type WebScrapeRequestFormat = (typeof WebScrapeRequestFormat)[keyof typeof WebScrapeRequestFormat];
