// This file was auto-generated by Fern from our API Definition.

export interface WebScrapeResponse {
    /** Extracted data based on the extract instructions */
    extractedData: Record<string, unknown>;
}
