// This file was auto-generated by Fern from our API Definition.

export type WebScrapeRequestBody =
    | {
          blockUrl?: string[] | undefined;
          cookies?:
              | {
                    name: string;
                    value: string;
                }[]
              | undefined;
          instructions: (
              | {
                    fill?:
                        | {
                              place: string;
                              value: string;
                          }
                        | undefined;
                }
              | {
                    click?: string | undefined;
                }
              | {
                    clickIfExist?: string | undefined;
                }
              | {
                    enter?: string | undefined;
                }
              | {
                    newTab?: boolean | undefined;
                }
              | {
                    moveToRelativeTab?: number | undefined;
                }
              | {
                    wait?: number | undefined;
                }
              | {
                    waitFor?: string | undefined;
                }
              | {
                    select?:
                        | {
                              place: string;
                              value: string;
                          }
                        | undefined;
                }
              | {
                    jsExe?: string | undefined;
                }
              | {
                    conditionalCheck?: Record<string, unknown>[] | undefined;
                }
              | {
                    clickButtonByValue?:
                        | {
                              place: string;
                              value: string;
                          }
                        | undefined;
                }
              | {
                    generalImageCaptcha?:
                        | {
                              imagePath?: string | undefined;
                              textField?: string | undefined;
                              imageUpdatePath?: string | undefined;
                              captchaFailedPath?: string | undefined;
                              model?:
                                  | ("mini-ocr-v1" | "Model20" | "Model05" | "Model141" | "Model150" | "Model102")
                                  | undefined;
                          }[]
                        | undefined;
                }
              | {
                    blockElement?: string[] | undefined;
                }
              | {
                    extract?:
                        | {
                              html?: string | undefined;
                              text?: string | undefined;
                              user_data?: string | undefined;
                          }
                        | undefined;
                }
              | {
                    fillImageCaptcha?: Record<string, unknown>[] | undefined;
                }
              | {
                    switchToIframe?: string | undefined;
                }
              | {
                    switchToParentFrame?: boolean | undefined;
                }
              | {
                    resolveAudioCaptcha?: Record<string, unknown> | undefined;
                }
              | {
                    screenshot?: (string | boolean) | undefined;
                }
              | {
                    saveimage?: string | undefined;
                }
          )[];
      }
    | {
          instructions: (
              | {
                    postForm?:
                        | {
                              selector?: string | undefined;
                              data?:
                                  | {
                                        name?: string | undefined;
                                    }
                                  | undefined;
                          }
                        | undefined;
                }
              | {
                    getForm?:
                        | {
                              selector?: string | undefined;
                              data?:
                                  | {
                                        name?: string | undefined;
                                    }
                                  | undefined;
                          }
                        | undefined;
                }
              | {
                    extract?:
                        | {
                              html?: string | undefined;
                              text?: string | undefined;
                          }
                        | undefined;
                }
              | {
                    getPage?: (string | boolean) | undefined;
                }
          )[];
      };
