// This file was auto-generated by Fern from our API Definition.

export const ZipcodeSearchByRadiusRequestUnit = {
    M: "m",
    Km: "km",
    Mi: "mi",
    Ft: "ft",
    Yd: "yd",
    In: "in",
} as const;
export type ZipcodeSearchByRadiusRequestUnit =
    (typeof ZipcodeSearchByRadiusRequestUnit)[keyof typeof ZipcodeSearchByRadiusRequestUnit];
