// This file was auto-generated by Fern from our API Definition.

export const ZipcodeSearchByRadiusRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type ZipcodeSearchByRadiusRequestFormat =
    (typeof ZipcodeSearchByRadiusRequestFormat)[keyof typeof ZipcodeSearchByRadiusRequestFormat];
