// This file was auto-generated by Fern from our API Definition.

export interface ZipcodeDistanceResponse {
    /** Number of distance results returned */
    results_count?: string | undefined;
    results?: ZipcodeDistanceResponse.Results.Item[] | undefined;
}

export namespace ZipcodeDistanceResponse {
    export type Results = Results.Item[];

    export namespace Results {
        export interface Item {
            /** ZIP/postal code */
            code?: string | undefined;
            /** Distance from the base ZIP/postal code */
            distance?: number | undefined;
        }
    }
}
