// This file was auto-generated by Fern from our API Definition.

export const ZipcodeSearchByRegionRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type ZipcodeSearchByRegionRequestFormat =
    (typeof ZipcodeSearchByRegionRequestFormat)[keyof typeof ZipcodeSearchByRegionRequestFormat];
