// This file was auto-generated by Fern from our API Definition.

export const ZipcodeDistanceRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type ZipcodeDistanceRequestFormat =
    (typeof ZipcodeDistanceRequestFormat)[keyof typeof ZipcodeDistanceRequestFormat];
