// This file was auto-generated by Fern from our API Definition.

export const ZipcodeDistanceMatchRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type ZipcodeDistanceMatchRequestFormat =
    (typeof ZipcodeDistanceMatchRequestFormat)[keyof typeof ZipcodeDistanceMatchRequestFormat];
