// This file was auto-generated by Fern from our API Definition.

export const ZipcodeLookupRequestFormat = {
    Json: "json",
    Xml: "xml",
} as const;
export type ZipcodeLookupRequestFormat = (typeof ZipcodeLookupRequestFormat)[keyof typeof ZipcodeLookupRequestFormat];
