// This file was auto-generated by Fern from our API Definition.

export interface ZipcodeSearchByRadiusResponse {
    /** Total number of ZIP/postal codes found within the radius */
    total_results?: number | undefined;
    /** Total number of pages available */
    total_pages?: number | undefined;
    /** Current page number */
    current_page?: number | undefined;
    /** Number of ZIP/postal codes in the current page */
    current_page_size?: number | undefined;
    results?: ZipcodeSearchByRadiusResponse.Results.Item[] | undefined;
}

export namespace ZipcodeSearchByRadiusResponse {
    export type Results = Results.Item[];

    export namespace Results {
        export interface Item {
            code?: string | undefined;
            region?: string | undefined;
            city?: string | undefined;
            district?: string | undefined;
            distance?: number | undefined;
        }
    }
}
