// This file was auto-generated by Fern from our API Definition.

import type * as ApifreaksApi from "../../index.js";

/**
 * @example
 *     {
 *         apiKey: "apiKey",
 *         asn: "asn"
 *     }
 */
export interface AsnWhoisLookupRequest {
    /** Your API key */
    apiKey: string;
    /** Format of the response. */
    format?: ApifreaksApi.AsnWhoisLookupRequestFormat;
    /** The Autonomous System Number (ASN) to retrieve WHOIS data for. Can be prefixed with 'as' or not. */
    asn: string;
}
