// This file was auto-generated by Fern from our API Definition.

import type * as ApifreaksApi from "../../index.js";

/**
 * @example
 *     {
 *         apiKey: "apiKey"
 *     }
 */
export interface AstronomyLookupV2Request {
    /** Your API key */
    apiKey: string;
    /** Format of the response. Can be "json" or "xml". */
    format?: ApifreaksApi.AstronomyLookupV2RequestFormat;
    /** Extract astronomy information using location (preferably city) */
    location?: string;
    /** Latitude to extract astronomy information using location coordinates */
    lat?: number;
    /** Longitude to extract astronomy information using location coordinates */
    long?: number;
    /** IPv4 or IPv6 address to extract astronomy information using IP address */
    ip?: string;
    /** Response language of "location" field in case of lookup through IP address only. */
    lang?: ApifreaksApi.AstronomyLookupV2RequestLang;
    /** Specific date (format YYYY-MM-DD) for which astronomy data is required */
    date?: string;
    /** Elevation above sea level at the location, in meters. The value should be between 0 meter and a maximum value of 10,000 meters. Negative value is set to 0. */
    elevation?: number;
    /** Time zone to receive all time-based data in your preferred local time. */
    time_zone?: string;
}
