// This file was auto-generated by Fern from our API Definition.

import type * as ApifreaksApi from "../../index.js";

/**
 * @example
 *     {
 *         apiKey: "apiKey",
 *         codes: ["codes"]
 *     }
 */
export interface BulkZipcodeLookupRequest {
    /** Your API key */
    apiKey: string;
    /** Format of the response. */
    format?: ApifreaksApi.BulkZipcodeLookupRequestFormat;
    /** Comma separated list of postal / zip codes. Max. 100 values. */
    codes: string[];
    /** Country code in ISO 3166-1 alpha-2 format. If not provided, search results will be returned from all countries. */
    country?: string;
}
