// This file was auto-generated by Fern from our API Definition.

import type * as ApifreaksApi from "../../index.js";

/**
 * @example
 *     {
 *         apiKey: "apiKey",
 *         urls: [{
 *                 url: "url"
 *             }]
 *     }
 */
export interface BulkScreenshotCaptureRequest {
    /** Your API key */
    apiKey: string;
    format?: ApifreaksApi.BulkScreenshotCaptureRequestFormat;
    /** List of website URLs to capture screenshots of */
    urls: BulkScreenshotCaptureRequest.Urls.Item[];
}

export namespace BulkScreenshotCaptureRequest {
    export type Urls = Urls.Item[];

    export namespace Urls {
        export interface Item {
            url: string;
            /** Accepts any additional properties */
            [key: string]: any;
        }
    }
}
