// This file was auto-generated by Fern from our API Definition.

import type * as ApifreaksApi from "../../index.js";

/**
 * @example
 *     {
 *         apiKey: "apiKey",
 *         numbers: [{
 *                 number: "+14155552671"
 *             }, {
 *                 number: "+447911123456"
 *             }, {
 *                 number: "+919876543210"
 *             }]
 *     }
 *
 * @example
 *     {
 *         apiKey: "apiKey",
 *         numbers: [{
 *                 number: "03301112233",
 *                 region: "PK"
 *             }, {
 *                 number: "number",
 *                 region: "GB"
 *             }, {
 *                 number: "number",
 *                 region: "IN"
 *             }]
 *     }
 *
 * @example
 *     {
 *         apiKey: "apiKey",
 *         numbers: [{
 *                 number: "+14155552671"
 *             }, {
 *                 number: "03301112233",
 *                 region: "PK"
 *             }, {
 *                 number: "0014155552671",
 *                 dialer_region: "AU"
 *             }]
 *     }
 */
export interface BulkPhoneValidateRequest {
    /** Your API key */
    apiKey: string;
    /** Specifies the desired format for the API response. Choose 'json' for a JSON object. If not provided, the API defaults to JSON format. */
    format?: ApifreaksApi.BulkPhoneValidateRequestFormat;
    /** Array of phone number objects. Maximum 100 per request. */
    numbers: BulkPhoneValidateRequest.Numbers.Item[];
}

export namespace BulkPhoneValidateRequest {
    export type Numbers = Numbers.Item[];

    export namespace Numbers {
        export interface Item {
            /** Phone number to validate. */
            number: string;
            /** Two-letter ISO country code. Required for local format numbers. Cannot be used together with dialer_region. */
            region?: string | undefined;
            /** Two-letter ISO country code of the dialing origin. Required for IDD format numbers. Cannot be used together with region. */
            dialer_region?: string | undefined;
        }
    }
}
