// This file was auto-generated by Fern from our API Definition.

import type * as ApifreaksApi from "../../index.js";

/**
 * @example
 *     {
 *         apiKey: "apiKey",
 *         uaStrings: ["uaStrings"]
 *     }
 */
export interface BulkUserAgentLookupRequest {
    /** Your API key */
    apiKey: string;
    /** Format of the response */
    format?: ApifreaksApi.BulkUserAgentLookupRequestFormat;
    /** Array of User-Agent strings to parse. Maximum 100 strings per request — exceeding that returns a 413. */
    uaStrings: string[];
}
