// This file was auto-generated by Fern from our API Definition.

import type * as ApifreaksApi from "../../index.js";

/**
 * @example
 *     {
 *         apiKey: "apiKey",
 *         emailData: [{
 *                 email: "email"
 *             }]
 *     }
 */
export interface BulkEmailValidateRequest {
    /** Your API key */
    apiKey: string;
    /** Format of the response */
    format?: ApifreaksApi.BulkEmailValidateRequestFormat;
    /** Array of email objects for bulk validation */
    emailData: BulkEmailValidateRequest.EmailData.Item[];
}

export namespace BulkEmailValidateRequest {
    export type EmailData = EmailData.Item[];

    export namespace EmailData {
        export interface Item {
            /** Email address to validate */
            email: string;
            /** Name associated with the email address */
            name?: string | undefined;
            /** IP address associated with the email address */
            ip?: string | undefined;
        }
    }
}
