// This file was auto-generated by Fern from our API Definition.

import type * as ApifreaksApi from "../../index.js";

/**
 * @example
 *     {
 *         apiKey: "apiKey",
 *         ips: ["ips"]
 *     }
 */
export interface BulkIpSecurityLookupRequest {
    /** Your API key */
    apiKey: string;
    /** Format of the response. */
    format?: ApifreaksApi.BulkIpSecurityLookupRequestFormat;
    /** Comma-separated list of fields to return. Supports dot notation (e.g. security.threat_score). */
    fields?: string;
    /** Comma-separated list of fields to remove from the response. Supports dot notation (e.g. security.is_tor). */
    excludes?: string;
    /** List of IP addresses to lookup */
    ips: string[];
}
