// This file was auto-generated by Fern from our API Definition.

import type * as ApifreaksApi from "../../index.js";

/**
 * @example
 *     {
 *         apiKey: "apiKey"
 *     }
 */
export interface CommoditySymbolsV2Request {
    /** Your API key */
    apiKey: string;
    /** Response format. Currently only `json` is supported. */
    format?: ApifreaksApi.CommoditySymbolsV2RequestFormat;
}
