// This file was auto-generated by Fern from our API Definition.

import type * as ApifreaksApi from "../../index.js";

/**
 * @example
 *     {
 *         apiKey: "apiKey",
 *         symbols: ["symbols"],
 *         date: "2023-01-15"
 *     }
 */
export interface CommodityHistoricalRatesV2Request {
    /** Your API key */
    apiKey: string;
    /** Response format. Currently only `json` is supported. */
    format?: ApifreaksApi.CommodityHistoricalRatesV2RequestFormat;
    /** Comma-separated list of commodity symbols. Case-insensitive; duplicates are deduplicated server-side, with one response entry and one credit charge per unique symbol. */
    symbols?: string | string[];
    /** Date in YYYY-MM-DD format. Data available from 1990 onwards. */
    date: string;
}
