// This file was auto-generated by Fern from our API Definition.

import type * as ApifreaksApi from "../../index.js";

/**
 * @example
 *     {
 *         apiKey: "apiKey",
 *         symbols: ["symbols"]
 *     }
 */
export interface CommodityLatestRatesV2Request {
    /** Your API key */
    apiKey: string;
    /** Response format. Currently only `json` is supported. */
    format?: ApifreaksApi.CommodityLatestRatesV2RequestFormat;
    /** Comma-separated list of commodity symbols (e.g., XAU, WTIOIL-SPOT). Case-insensitive; duplicates are deduplicated server-side, with one response entry and one credit charge per unique symbol. */
    symbols?: string | string[];
    /** Target currency for the exchange rate. If omitted (or set to `default`), the default quote currency of each commodity is used. Requires a premium plan; ignored on lower-tier plans. */
    quote?: string;
}
