// This file was auto-generated by Fern from our API Definition.

import type * as ApifreaksApi from "../../index.js";

/**
 * @example
 *     {
 *         apiKey: "apiKey",
 *         symbols: ["symbols"],
 *         startDate: "2023-01-15",
 *         endDate: "2023-01-15"
 *     }
 */
export interface CommodityFluctuationV2Request {
    /** Your API key */
    apiKey: string;
    /** Response format. Currently only `json` is supported. */
    format?: ApifreaksApi.CommodityFluctuationV2RequestFormat;
    /** Comma-separated list of commodity symbols. Case-insensitive; duplicates are deduplicated server-side, with one response entry and one credit charge per unique symbol. */
    symbols?: string | string[];
    /** Start date (YYYY-MM-DD) */
    startDate: string;
    /** End date (YYYY-MM-DD) */
    endDate: string;
}
