// This file was auto-generated by Fern from our API Definition.

import type * as ApifreaksApi from "../../index.js";

/**
 * @example
 *     {
 *         apiKey: "apiKey",
 *         date: "2023-01-15"
 *     }
 */
export interface CurrencyHistoricalRatesRequest {
    /** Your API key */
    apiKey: string;
    /** Format of the response. */
    format?: ApifreaksApi.CurrencyHistoricalRatesRequestFormat;
    /** Base currency for rate calculations */
    base?: string;
    /** Comma separated list of desired currency codes */
    symbols?: string | string[];
    /** Specific date in YYYY-MM-DD format */
    date: string;
}
