// This file was auto-generated by Fern from our API Definition.

import type * as ApifreaksApi from "../../index.js";

/**
 * @example
 *     {
 *         apiKey: "apiKey",
 *         from: "from",
 *         to: "to",
 *         date: "2023-01-15"
 *     }
 */
export interface CurrencyConvertHistoricalRequest {
    /** Your API key */
    apiKey: string;
    /** Format of the response. */
    format?: ApifreaksApi.CurrencyConvertHistoricalRequestFormat;
    /** From currency symbol */
    from: string;
    /** To currency symbol */
    to: string;
    /** The Amount to be converted */
    amount?: number;
    /** specific date (format YYYY-MM-DD) of which exchange rates is used. */
    date: string;
}
