// This file was auto-generated by Fern from our API Definition.

import type * as ApifreaksApi from "../../index.js";

/**
 * @example
 *     {
 *         apiKey: "apiKey",
 *         from: "from",
 *         to: "to"
 *     }
 */
export interface CurrencyConvertLatestRequest {
    /** Your API key */
    apiKey: string;
    /** Format of the response. */
    format?: ApifreaksApi.CurrencyConvertLatestRequestFormat;
    /** Source currency code */
    from: string;
    /** Target currency code */
    to: string;
    /** Amount to convert */
    amount?: number;
    /** Exchange rates update period (1d=daily, 1h=hourly, 10m=10 minutes, 1m=1 minute) */
    updates?: ApifreaksApi.CurrencyConvertLatestRequestUpdates;
}
