// This file was auto-generated by Fern from our API Definition.

import type * as ApifreaksApi from "../../index.js";

/**
 * @example
 *     {
 *         apiKey: "apiKey",
 *         domainName: "domainName"
 *     }
 */
export interface DomainSslLookupRequest {
    /** Your API key */
    apiKey: string;
    /** Format of the response. */
    format?: ApifreaksApi.DomainSslLookupRequestFormat;
    /** Domain name or URL whose SSL certificate lookup is required */
    domainName: string;
    /** Set to true to get the raw openSSL response of the domain */
    sslRaw?: boolean;
}
