// This file was auto-generated by Fern from our API Definition.

import type * as ApifreaksApi from "../../index.js";

/**
 * @example
 *     {
 *         apiKey: "apiKey",
 *         domainName: "domainName"
 *     }
 */
export interface DomainWhoisLookupV2Request {
    /** Your API key */
    apiKey: string;
    /** Format of the response. */
    format?: ApifreaksApi.DomainWhoisLookupV2RequestFormat;
    /** Domain name to retrieve WHOIS data for (e.g. example.com). */
    domainName: string;
}
