// This file was auto-generated by Fern from our API Definition.

import type * as ApifreaksApi from "../../index.js";

/**
 * @example
 *     {
 *         apiKey: "apiKey",
 *         "host-name": "host-name",
 *         type: ["type"]
 *     }
 */
export interface DomainDnsHistoryRequest {
    /** Your API key */
    apiKey: string;
    /** Format of the response. */
    format?: ApifreaksApi.DomainDnsHistoryRequestFormat;
    /** Hostname or URL whose historical DNS records are required */
    "host-name": string;
    /**
     * A comma-separated list of DNS record types for lookup.
     * Possible values: A, AAAA, MX, NS, SOA, SPF, TXT, CNAME, or all
     */
    type?: string | string[];
    /** Page number for paginated results */
    page?: number;
}
