// This file was auto-generated by Fern from our API Definition.

import type * as ApifreaksApi from "../../index.js";

/**
 * @example
 *     {
 *         apiKey: "apiKey"
 *     }
 */
export interface GeolocationLookupRequest {
    /** Your API key */
    apiKey: string;
    /** Format of the response. */
    format?: ApifreaksApi.GeolocationLookupRequestFormat;
    /** IPv4, IPv6, or hostname for geolocation lookup */
    ip?: string;
    /** Response language for location fields */
    lang?: ApifreaksApi.GeolocationLookupRequestLang;
    /** Comma separated list of fields to include in response */
    fields?: string;
    /** Comma separated list of fields to exclude from response */
    excludes?: string;
    /** Additional data to include (location, network, security, currency, time_zone, user_agent, country_metadata , hostname, liveHostname, hostnameFallbackLivet) */
    include?: string;
}
