// This file was auto-generated by Fern from our API Definition.

import type * as ApifreaksApi from "../../index.js";

/**
 * @example
 *     {
 *         apiKey: "apiKey",
 *         country: "country"
 *     }
 */
export interface GetCountryDetailsRequest {
    /** Your API key */
    apiKey: string;
    /** Format of the response */
    format?: ApifreaksApi.GetCountryDetailsRequestFormat;
    /** Country code in ISO 3166-1 alpha-2 format. */
    country: string;
}
