// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         apiKey: "apiKey",
 *         text: "The global mental is health crisis is now a serious and compelex problem. It need quick and ongoing action from policymakers, healthcare workers, and the whole society."
 *     }
 */
export interface GrammarDetectRequest {
    /** Your API key */
    apiKey: string;
    /** Text to analyze for grammar errors */
    text: string;
}
