// This file was auto-generated by Fern from our API Definition.

import type * as ApifreaksApi from "../../index.js";

/**
 * @example
 *     {
 *         apiKey: "apiKey"
 *     }
 */
export interface IpSecurityLookupRequest {
    /** Your API key */
    apiKey: string;
    /** Format of the response. */
    format?: ApifreaksApi.IpSecurityLookupRequestFormat;
    /** A valid IPv4 or IPv6 address to look up. If omitted, the API uses the public IP of the requesting client. */
    ip?: string;
    /** Comma-separated list of fields to return. Supports dot notation (e.g. security.threat_score). */
    fields?: string;
    /** Comma-separated list of fields to remove from the response. Supports dot notation (e.g. security.is_tor). */
    excludes?: string;
}
