// This file was auto-generated by Fern from our API Definition.

import type * as ApifreaksApi from "../../index.js";

/**
 * @example
 *     {
 *         apiKey: "apiKey"
 *     }
 */
export interface MarineWeatherRequest {
    /** Your API key */
    apiKey: string;
    /** Response format returned by the API. */
    format?: ApifreaksApi.MarineWeatherRequestFormat;
    /** Starting date for marine forecast data in YYYY-MM-DD format. Forecast dates must be current or future dates only. Past dates are not allowed for forecast data. The difference between endDate and startDate must not exceed 16 days. */
    startDate?: string;
    /** End date for marine forecast data in YYYY-MM-DD format. Forecast dates must be current or future dates only. Past dates are not allowed for forecast data. The difference between endDate and startDate must not exceed 16 days. */
    endDate?: string;
    /** City name, place name, or full address. */
    location?: string;
    /** Latitude of the location. */
    lat?: number;
    /** Longitude of the location. */
    long?: number;
    /** IP(v4 or v6) address for location inference. */
    ip?: string;
    /** Precision of the marine data. */
    precision?: ApifreaksApi.MarineWeatherRequestPrecision;
    /** Timezone for the results. */
    timezone?: string;
}
