// This file was auto-generated by Fern from our API Definition.

import type * as core from "../../../core/index.js";
import type * as ApifreaksApi from "../../index.js";

/**
 * @example
 *     {
 *         apiKey: "apiKey",
 *         user_password: "user_password",
 *         restrictions: ["print_high"]
 *     }
 */
export interface PdfRestrictRequest {
    /** Your API key */
    apiKey: string;
    /** Specifies the desired format for the API response. Choose 'json' for a JSON object or 'xml' for an XML structure. */
    format?: ApifreaksApi.PdfRestrictRequestFormat;
    /** The unique ID of a PDF file already uploaded to the API Freaks server. Use this as an alternative to uploading a new file directly. */
    file_id?: string;
    /** If set to `true`, the input file(s) will be permanently deleted from the server immediately after the output PDF is generated. */
    destroy?: boolean;
    /** The desired name for the output restricted PDF file. If not provided, a default name will be assigned. */
    output?: string;
    /** The password to unlock the input file if it is already secured. Provide the owner password if available; otherwise, the user password. The owner password takes precedence. Password Length should be between 6 and 128 characters. */
    file_password?: string;
    /** Sets the password users will use to open the PDF. If this is not set, only the owner password will be configured, and anyone can open the PDF file with the provided restrictions enabled. Password Length should be between 6 and 128 characters. */
    user_password: string;
    /** Sets the password that allows full access to the PDF (e.g., removing restrictions). If not provided, the `user_password` (if set) will also be used as the owner password. Password Length should be between 6 and 128 characters. */
    owner_password?: string;
    /**
     * A comma-separated list of restrictions to apply to the PDF. These define what the end-user is *not* allowed to do with the PDF. Available options are:
     *
     *
     * * **print_high** – Disables high-quality printing.
     * * **print_low** – Disables low-resolution printing.
     * * **edit_document_assembly** – Prevents reordering or inserting pages.
     * * **fill_form_fields** – Disallows filling in PDF form fields.
     * * **edit_annotations** – Disables adding or modifying annotations or comments.
     * * **modify_content** – Prevents modifying existing content in the PDF.
     * * **copy_and_extract_content** – Disables copying text or images from the PDF.
     * * **use_accessibility** – Prevents screen readers or accessibility tools from accessing content.
     */
    restrictions?: ApifreaksApi.PdfRestrictRequestRestrictionsItem | ApifreaksApi.PdfRestrictRequestRestrictionsItem[];
    /** The URL to which the webhook notification will be sent after the task is completed. */
    webhook_url?: string;
    /** If true, a notification will also be sent by email in case the webhook request fails all the retries.  The email notification will be sent to the requesting user or their organization’s admin if part of one. */
    webhook_failure_notification?: boolean;
    /** Optional custom header for webhook requests. Format: `Key:Value` (e.g., `Authorization:Bearer token123`). This will be sent as an HTTP header in the webhook call. */
    "X-Webhook-Authorization"?: string;
    /** The PDF file to be processed. If this parameter is not provided, you must specify `file_id` to use a previously uploaded file. */
    file?: core.file.Uploadable | undefined;
}
