// This file was auto-generated by Fern from our API Definition.

import type * as ApifreaksApi from "../../index.js";

export interface PdfUploadBinaryRequest {
    /** Your API key */
    apiKey: string;
    /** Specifies the desired format for the API response. Choose 'json' for a JSON object or 'xml' for an XML structure. */
    format?: ApifreaksApi.PdfUploadBinaryRequestFormat;
    /**
     * The desired name for the uploaded PDF file. This name will be used for storage on the server.
     *
     *
     *  **NOTE**: Please ensure file_name has extension `.pdf`.
     */
    file_name: string;
}
