// This file was auto-generated by Fern from our API Definition.

import type * as ApifreaksApi from "../../index.js";

/**
 * @example
 *     {
 *         apiKey: "apiKey",
 *         country: "country",
 *         region: "region"
 *     }
 */
export interface ZipcodeSearchByRegionRequest {
    /** Your API key */
    apiKey: string;
    /** Format of the response. */
    format?: ApifreaksApi.ZipcodeSearchByRegionRequestFormat;
    /** Country code in ISO 3166-1 alpha-2 format. */
    country: string;
    /** Name of the region, state or province associated with the country. */
    region: string;
    /** Page no. to retrieve paginated results. */
    page?: number;
}
