// This file was auto-generated by Fern from our API Definition.

import type * as ApifreaksApi from "../../index.js";

/**
 * @example
 *     {
 *         apiKey: "apiKey",
 *         city: "city",
 *         country: "country"
 *     }
 */
export interface ZipcodeSearchByCityRequest {
    /** Your API key */
    apiKey: string;
    /** Format of the response. */
    format?: ApifreaksApi.ZipcodeSearchByCityRequestFormat;
    /** Name of the city in which we want to find zipcodes in. */
    city: string;
    /** Country code in ISO 3166-1 alpha-2 format. */
    country: string;
    /** Name of the state or province associated with the country. */
    state_name?: string;
    /** Page number to retrieve paginated results. */
    page?: number;
}
