// This file was auto-generated by Fern from our API Definition.

import type * as core from "../../core/index.js";
import * as errors from "../../errors/index.js";
import type * as ApifreaksApi from "../index.js";

export class ProxyAuthenticationRequiredError extends errors.ApifreaksApiError {
    constructor(body: ApifreaksApi.ProxyAuthenticationRequiredErrorBody, rawResponse?: core.RawResponse) {
        super({
            message: "ProxyAuthenticationRequiredError",
            statusCode: 407,
            body: body,
            rawResponse: rawResponse,
        });
        Object.setPrototypeOf(this, new.target.prototype);
        if (Error.captureStackTrace) {
            Error.captureStackTrace(this, this.constructor);
        }

        this.name = this.constructor.name;
    }
}
